### ISSUE TITLE
java.nio.file.FileSystemException: D:\<path-to-project>\.gogradle\project_gopath\src\<package-name>: A required privilege is not held by the client.

### ISSUE THREAD

**Issue by remal** [gogradle/gogradle#108]
My OS is Windows 10. Project files are on drive D: (system drive - C:)

I'm getting this exception:
```
java.nio.file.FileSystemException: D:\<path-to-project>\.gogradle\project_gopath\src\<package-name>: A required privilege is not held by the client.
	at com.github.blindpirate.gogradle.build.DefaultBuildManager.createSymbolicLink(DefaultBuildManager.java:132)
```

I've heart smth about UAC, but my system admin forbided security changes.

**Comment by blindpirate** [comment]
Gogradle will make a symbolic link in project directory and treat it as project-level `GOPATH`, it seems your OS security strategy forbids to do this. So you have two choice:

- Give it the privilege. See [https://stackoverflow.com/questions/23217460/how-to-create-soft-symbolic-link-using-java-nio-files](https://stackoverflow.com/questions/23217460/how-to-create-soft-symbolic-link-using-java-nio-files).

- Try to use a global `GOPATH` in [canonical way](https://golang.org/doc/code.html#Workspaces).

**Comment by blindpirate** [comment]
I would close this issue. Hope you've already solved it.
