### ISSUE TITLE
Task with name 'cleanIdeaProject' not found in project

### ISSUE THREAD

**Issue by gtinjr** [gogradle/gogradle#111]
When applying the plugin in a subproject, it gives the following error:
Task with name 'cleanIdeaProject' not found in project

It seems that the idea plugin does not add cleanIdeaProject to subprojects the only thing it adds is

gw tasks --all | egrep -i idea
cleanIdea - Cleans IDEA project files (IML, IPR)
idea - Generates IDEA project files (IML, IPR, IWS)
cleanIdeaModule
ideaModule - Generates IDEA module files (IML)

**Comment by blindpirate** [comment]
Which version are you using? I believe this issue should be solved in latest version `0.6.2`.

**Comment by gtinjr** [comment]
With 0.6.2 and gradle 3.5 I get the following error:


* What went wrong:
An exception occurred applying plugin request [id: 'com.github.blindpirate.gogradle', version: '0.6.2']
> Failed to apply plugin [id 'com.github.blindpirate.gogradle']
   > Cannot add task ':search:backend:proxy:gateway:build' as a task with that name already exists.



Here is my build.gradle

plugins {
    id 'com.github.blindpirate.gogradle' version '0.6.2'
}
apply plugin: 'idea'

golang {
    packagePath = 'company.com/reverse_proxy_gateway'
}

dependencies {
    goVersion = '1.8.3'
    golang {
        build 'github.com/elazarl/go-bindata-assetfs/...'
    }
}

**Comment by blindpirate** [comment]
Well, it seems you've already solved the `cleanIdeaProject` issue. Task name conflict can be solved by [this doc](https://github.com/gogradle/gogradle/blob/master/docs/tasks.md#task-name-conflict).

And in my experience, you might as well delete `.gradle` directory before doing this because there is cache stuff in it.

**Comment by blindpirate** [comment]
And I guess `goVersion = '1.8.3'` should be in `golang` block instead of `dependencies` block.

**Comment by gtinjr** [comment]
It is working perfectly. Thanks for this great plugin!!!

**Comment by blindpirate** [comment]
I'm pleased to see that. Please let me know if there's any question.
