### ISSUE TITLE
goTest Faile, but execute go test successfully

### ISSUE THREAD

**Issue by JackTiger** [gogradle/gogradle#120]
```
root@slave2:/home/golang/src/code.xxxx.com/prp/cell# go test -v code.xxxx.com/prp/cell/utils
=== RUN   TestInstantiate
=== RUN   TestInstantiate/test:_int
=== RUN   TestInstantiate/test:_*int
=== RUN   TestInstantiate/test:_custom_type
=== RUN   TestInstantiate/test:_unknown
2017/07/20 16:17:43 instantiate unknown err: type not found in executable image: unknown
--- PASS: TestInstantiate (0.00s)
    --- PASS: TestInstantiate/test:_int (0.00s)
    --- PASS: TestInstantiate/test:_*int (0.00s)
    --- PASS: TestInstantiate/test:_custom_type (0.00s)
    --- PASS: TestInstantiate/test:_unknown (0.00s)
=== RUN   TestExtractFunc
=== RUN   TestExtractFunc/test:_defined
=== RUN   TestExtractFunc/test:_undefined
2017/07/20 16:17:43 extract func err, name: code.xxxx.com/prp/cell/utils.world, type: func() string
--- PASS: TestExtractFunc (0.00s)
    --- PASS: TestExtractFunc/test:_defined (0.00s)
    --- PASS: TestExtractFunc/test:_undefined (0.00s)
=== RUN   TestDecode
--- PASS: TestDecode (0.00s)
PASS
ok  	code.xxxx.com/prp/cell/utils	0.019s

```

我用最新的版本Gogradle 0.6.4在构建时，执行goTest，结果是Failed, 我在本地执行go test ,打出的日志如上面，是不是不支持这种格式的解析的，从测试报告看，有6个case失败了，因为没有找到匹配的paas

**Comment by blindpirate** [comment]
正常的应该是
```
=== RUN 1
--- PASS 1

=== RUN 2
--- PASS 2
```
可能是由于并发的原因，你给出的结果完全是乱的，所以解析会出问题。

**Comment by JackTiger** [comment]
测试Case:

```
func TestInstantiate(t *testing.T) {
	cases := []struct {
		n   string
		typ string
		val interface{}
	}{
		{"test: int", "int", int(0)},
		{"test: *int", "*int", new(int)},
		{"test: custom type", "*code.xxxxx.com/prp/xxxx/utils.x", new(x)},
		{"test: unknown", "unknown", nil},
	}
	for _, tc := range cases {
		t.Run(tc.n, func(t *testing.T) {
			v := Instantiate(tc.typ)
			assert.Equal(t, v, tc.val)
		})
	}
}
```

**Comment by blindpirate** [comment]
这是t.Run递归调用引起的，暂时不会考虑处理这种情况的日志。

**Comment by JackTiger** [comment]
我使用0.6.2版本测试这种case，是没有问题的，0.6.2版本上面这种情况是按照1个case来处理，我觉得很合理。所以我怀疑是新版本为了解决goroutine中运行测试用例的问题，带入的新问题，我觉得你那边可以规避这个问题。 你可以本地验证一下

**Comment by blindpirate** [comment]
给case的时候麻烦给直接可以运行的，你的代码里Instantiate, util.x都是什么，需要我自己编吗？

**Comment by JackTiger** [comment]
不好意思，你可以把这些去掉，我之前只是想说明是这种格式的，应该很好构造出来的。

**Comment by JackTiger** [comment]
需要的话，我晚上回去直接给你一个可以运行的case，另外使用0.6.2版本，会把这个作为1个case，新版本应该会认为是5个case

**Comment by blindpirate** [comment]
之前上过你的当，你的描述和实际出入很大。所以我只看可以跑的case，不会试图去构造一个“很好构造出来的case”。

**Comment by JackTiger** [comment]
无语，这能看出来的呀，我晚上写一个发出来

**Comment by blindpirate** [comment]
恕我直言，长久以来，在和你的交流过程中，我感到你的技术能力和沟通能力都不足：

- 基础能力差，正则表达式应该是基本能力，而你被同一个问题绊倒两次，而且明显无法自己排查解决问题；
- 不喜欢读文档，连go的官方文档都没有深入阅读，从而在文档中明确指出的命令行参数上遇到障碍；
- 不善用搜索，凡事都喜欢通过询问的方式来解决；
- 不喜欢深入研究技术细节，同一个问题经常需要询问很多遍。

有关沟通的问题：

- 聊天过程中经常出现病句，并且自己没有意识到，时常需要我提醒你我没有看懂；
- 假设对方了解自己提出的问题，不及时给出上下文；
- 经常使用自己创造的术语而不进一步解释，增加沟通的成本；
- 喜欢自行归纳总结原因，而不是给出代码或者完整的上下文和日志。

因此，在遇到你提交的问题时，我坚持一定要你提交代码，因为我不相信你的判断和表达能力，这也是你多次用实际行动增加沟通成本、浪费我们双方时间的后果。

话比较直，这是我很久以来对你的印象，望理解。

给你提供几个我向别的项目提交的issue，我希望你在提出问题时：

- 不要假设对方了解自己的问题，对方可能对你的情况一无所知，请站在别人的立场上思考问题；
- 给出原始代码或者详细的复现步骤，如果可能，直接开一个新的仓库存放代码片段，尽量避免用自己的语言描述问题，避免“你试试，应该很好构造”，“很明显啊”这种话。Talk is cheap, show me the code.

[https://github.com/gradle/gradle/issues/1861](https://github.com/gradle/gradle/issues/1861)
[https://github.com/gradle/gradle/issues/2315](https://github.com/gradle/gradle/issues/2315)
[https://youtrack.jetbrains.com/issue/GO-4118](https://youtrack.jetbrains.com/issue/GO-4118)

**Comment by JackTiger** [comment]
感谢你的反馈，我突然意识到我们之间的沟通出现了这么严重的误会。
有关技术和沟通能力：
这个我是非常抱歉，我不是Java系的，应该是4月份刚接触Gradle，所以对相关的语法不熟，而且我也没有太多的时间去深入学习这门语言，可能与我司的情况有关，有时是多个工作同时并行操作，所以短期内特别是计划节奏压得特别紧的情况下，没有太多的时间深入研究这门技术。

对于Go语言这块，我不是很赞同你说的，技术的研究没有全集的，不是说你看到了，就能说明什么问题，只能说你工作正好涉及到这块，你平时工作都接触不到的一些技术点，你会去研究吗？搞语言和搞工程本身就是两码事。当然你能提出你的建议，我还是非常感谢的！

有关沟通这块：
你可能误解我了，我很早就跟你说过，我司的一些特殊情况，很多构建场景非常复杂，不是简单的能还原出场景的。而且出了问题，找你定位，我也在能给你一个好的case而感到烦恼：
1.日志不能直接发给你
2.我也非常迫切希望能构建一个能复现的场景，做程序员的谁不希望有这样一个轻松定位的手段呢。
3.我不知道你那边跟我的沟通方式主要在PC上还是哪种方式，我在工作时间，通过手机微信去描述一个非常复杂的场景，我也觉得不是合适，经常出错，导致你那边的理解不能跟我这边同步。这点我跟你说声非常抱歉

Issue的问题，我之前也在其他github工程上提过issue，所以感谢你的建议。
https://github.com/minio/minio/issues/3210， https://github.com/minio/minio/issues/3159 https://github.com/alecthomas/gometalinter/issues/283

其实长期接触以来，不管怎么说，我们还是一起解决了很多问题的，我这边提出的issue以及Bug，我觉得应该是对你还是有很大帮助的，很多场景的case以及gogradle的构建能力。

我前面可能太在意快速解决一个我认为可能是Bug的问题，所以总想着快速能反馈到你那边，可能我使用的这种方式给你那边造成了很大的困扰和麻烦，后面我会尝试使用你认可的一种方式跟你反馈，感谢你一直对我这边的支持！

**Comment by blindpirate** [comment]
有关技术的问题，我给你举几个小例子吧。

- 我认为，不管什么语言，正则表达式是基本能力，而你明显被同一个问题绊倒了两次
- 你问我String有没有contains方法，我认为，即使你不是写Java出身，这也可以通过一个简单的搜索解决，无需发问，所以我选择不回答你的问题
- 你碰到过jdk版本问题并提交了issue，而这明显是可以通过搜索解决的问题
- 你碰到过`go build <import path>`的问题，而文档里的用法写的非常清楚，但是明显你没有阅读文档

以上这些事情使我认为，在技术上，你需要提高的是解决问题的能力，和你的背景无关。

另外，不知你有没有发现，你的两个issue中，第一句都有语法错误？

`I have find` -> `I have found`

**Comment by JackTiger** [comment]
好的，谢谢你的建议。我发现你是非常细心和执着的人，做程序员应该具备你这种能力。我有时可能再在意能快速解决问题，而忽略自身的提高了。我希望我后面的一些方式能改变你对我的看法，不过可能会很难，我还是希望试一试。

**Comment by JackTiger** [comment]
言归正传，我还是回到这个issue本身的问题上：

我刚在本地构架了一个测试Demo，我使用的Mac OS，Go version:1.8, 我的case code如下：(比较简单我就直接贴代码了)

```
demo.go

package lib

func Add(x int, y int) (z int) {
    z = x + y
    return
}

demo_test.go

package lib
import "testing"

func TestInstantiate(t *testing.T) {
        cases := []struct {
                n string
                a   int
                b   int
                result int
        }{
		{"test: 1", 1, 1, 2},
		{"test: 2", 2, 2, 4},
		{"test: 3", 3, 3, 6},
	}
	for _, tc := range cases {
		t.Run(tc.n, func(t *testing.T) {
			v := Add(tc.a, tc.b)
			if v != tc.result {
            		   t.Errorf("Add Error \n");
                         }
		})
	}
}

```

我在本地执行 go test -v ./..., 输出结果：

```
liyuan:demo Ly$ go test -v ./...
=== RUN   TestInstantiate
=== RUN   TestInstantiate/test:_1
=== RUN   TestInstantiate/test:_2
=== RUN   TestInstantiate/test:_3
--- PASS: TestInstantiate (0.00s)
    --- PASS: TestInstantiate/test:_1 (0.00s)
    --- PASS: TestInstantiate/test:_2 (0.00s)
    --- PASS: TestInstantiate/test:_3 (0.00s)
PASS
ok  	demo	0.008s
```

这种场景的测试用例，gogradle0.6.2版本是支持的，但是最新的gogradle版本执行goTest任务会失败，只有TestInstantiate/test:_3会成功，TestInstantiate/test:_1以及TestInstantiate/test:_2由于没有直接匹配到结果，所以报错了。

```
=== RUN   TestInstantiate/test:_3
--- PASS: TestInstantiate (0.00s)
```

麻烦你本地分析一下原因，谢谢！

**Comment by blindpirate** [comment]
好的，我已经上床了，明天看一下。

**Comment by blindpirate** [comment]
在`0.6.2`中，一个测试结果是从`=== RUN`开始，到`--- PASS`结束的，因此上面的结果会被识别成：

```
▽▽▽▽▽▽▽测试结果1开始▽▽▽▽▽▽▽
=== RUN   TestInstantiate
=== RUN   TestInstantiate/test:_1
=== RUN   TestInstantiate/test:_2
=== RUN   TestInstantiate/test:_3
--- PASS: TestInstantiate (0.00s)
△△△△△△△测试结果1结束△△△△△△△
    --- PASS: TestInstantiate/test:_1 (0.00s)
    --- PASS: TestInstantiate/test:_2 (0.00s)
    --- PASS: TestInstantiate/test:_3 (0.00s)
PASS
ok  	demo	0.008s
```
其他部分丢弃。在 #112 中，我们发现一个测试结果可以没有`---PASS`，因此测试结果的结束是以`===RUN`或者`--- PASS`为标志的，所以在之后的版本中，上面的结果被识别为：

```
▽▽▽▽▽▽▽测试结果1开始▽▽▽▽▽▽▽
=== RUN   TestInstantiate
△△△△△△△测试结果1结束△△△△△△△
▽▽▽▽▽▽▽测试结果2开始▽▽▽▽▽▽▽
=== RUN   TestInstantiate/test:_1
△△△△△△△测试结果2结束△△△△△△△
▽▽▽▽▽▽▽测试结果3开始▽▽▽▽▽▽▽
=== RUN   TestInstantiate/test:_2
△△△△△△△测试结果3结束△△△△△△△
▽▽▽▽▽▽▽测试结果4开始▽▽▽▽▽▽▽
=== RUN   TestInstantiate/test:_3
--- PASS: TestInstantiate (0.00s)
△△△△△△△测试结果4结束△△△△△△△
    --- PASS: TestInstantiate/test:_1 (0.00s)
    --- PASS: TestInstantiate/test:_2 (0.00s)
    --- PASS: TestInstantiate/test:_3 (0.00s)
PASS
ok  	demo	0.008s
```

并且，如果没有找到`--- PASS`或者`--- FAIL`，测试会被认为失败。

关于这个问题，我没有很好的解决方案，因此暂时无法解决。根据[这里](https://github.com/golang/go/issues/2981)，go 1.10会引入test结果的json输出，可以从根本上解决此问题。

**Comment by JackTiger** [comment]
谢谢反馈！
我上午也思考了解决方式，简单描述一下我的想法(我们可以讨论一下)：

方案1：
根据名字匹配来判断case运行结束：(按照你的描述场景，我展开一下)

```
我使用一个数组来记录需要测试的CASE：
▽▽▽▽▽▽▽测试结果1开始▽▽▽▽▽▽▽
=== RUN   TestInstantiate                          1. TestInstantiate存入数组，作为测试case开始的标识                 
▽▽▽▽▽▽▽测试结果2开始▽▽▽▽▽▽▽
=== RUN   TestInstantiate/test:_1              2.  TestInstantiate/test:_1存入数组，作为测试case开始的标识
▽▽▽▽▽▽▽测试结果3开始▽▽▽▽▽▽▽     
=== RUN   TestInstantiate/test:_2              3. TestInstantiate/test:_2存入数组，作为测试case开始的标识
▽▽▽▽▽▽▽测试结果4开始▽▽▽▽▽▽▽
=== RUN   TestInstantiate/test:_3              4. TestInstantiate/test:_2存入数组，作为测试case开始的标识
--- PASS: TestInstantiate (0.00s)                  5. TestInstantiate测试结束，将TestInstantiate 从数组中移除
△△△△△△△测试结果4结束△△△△△△△              
    --- PASS: TestInstantiate/test:_1 (0.00s)   6. TestInstantiate/test:_1测试结束，将TestInstantiate/test:_1从数组中移除
    --- PASS: TestInstantiate/test:_2 (0.00s)   7. TestInstantiate/test:_2测试结束，将TestInstantiate/test:_2从数组中移除
    --- PASS: TestInstantiate/test:_3 (0.00s)   8. TestInstantiate/test:_3测试结束，将TestInstantiate/test:_3从数组中移除
PASS                                                             9.数据中剩余的Item都是没有匹配到结果的，直接认为测试失败
ok  	demo	0.008s

```

方案2：从输出的日志来看，TestInstantiate， TestInstantiate/test:_1， TestInstantiate/test:_2， TestInstantiate/test:_3是有一定的关系的，都是以TestInstantiate名字开头，所以如果以同一个名字开头的可以作为一组case统一处理，以TestInstantiate的测试结果为返回结果(我本地测试过，如果有一个失败了，测试结果也是失败的)
```
▽▽▽▽▽▽▽测试结果1开始▽▽▽▽▽▽▽
=== RUN   TestInstantiate
▽▽▽▽▽▽▽测试结果sub1开始▽▽▽▽▽▽▽
=== RUN   TestInstantiate/test:_1
▽▽▽▽▽▽▽测试结果sub2开始▽▽▽▽▽▽▽
=== RUN   TestInstantiate/test:_2
▽▽▽▽▽▽▽测试结果sub3开始▽▽▽▽▽▽▽
=== RUN   TestInstantiate/test:_3
--- PASS: TestInstantiate (0.00s)
△△△△△△△测试结果TestInstantiate结束△△△△△△△
```

我比较推荐方案二。

**Comment by blindpirate** [comment]
没有那么简单。

- 在你看到一个`=== RUN`时，你并不知道这是一个正常的子测试开始的标志还是一个新测试开始的标志（因为上一个测试可能异常退出而没有留下痕迹）。同时，你这个case是最简单的情况，因为它很干净。但是实际中，不同的`===RUN`直接可能夹杂着测试的正常日志输出，这些输出会严重干扰字符串匹配。
- 子测试嵌套子测试的情况呢？注意，在任意一层嵌套中，它都可能丢出panic而没有对应的`---PASS`或者`---FAIL`存在。
- 子测试名字的pattern实际上来源于`Run`的第一个参数，所以并不一定有什么规律。判断是不是以同一个名字开头非常不靠谱，比如，`Test`的子测试名字叫`a/a`，`Test`的名为`a`的子测试又有一个名为`a`的子测试，它们显示的名字相同，都是`Test/a/a`，完全无法区分。

这只是我随便想到的一些情况，只是想想，就知道要支持这种情况必然非常复杂，并且要花大量的精力去写测试和调试。我说的"没有很好的解决方案"不是指技术上的解决方案，如果我喜欢，我当然可以用ANTLR写一个parser去处理它们。在没有一个简单、性价比高的方案值得我去实现之前，我宁愿明确表示，不支持这种嵌套`Run`的场景。

如果你觉得你的方案可行，不妨写一点代码，用任意语言去实现它，你会发现，它的复杂度超过了你的想象。

**Comment by JackTiger** [comment]
谢谢你的反馈，你考虑问题的方式很全面，我更多的是站在已有的场景上去解决问题，的确考虑不是很周到。

**Comment by JackTiger** [comment]
暂时使用0.6.2的版本，不考虑goroutine中运行TestCase Panic的情况。
