### ISSUE TITLE
The notion of `internal` tasks is not meaningful to end users

### ISSUE THREAD

**Issue by bmuschko** [gogradle/gogradle#125]
Tasks that are not necessarily relevant to end users should not define a `group` and `description` property. `Internal` does not mean much to users. `gradle tasks` will not render those tasks anyway.

```
Internal tasks
--------------
installDependencies - Internal usage only.
resolveBuildDependencies - Internal usage only.
resolveTestDependencies - Internal usage only.
```

Related to https://github.com/gogradle/gogradle/issues/117

**Comment by blindpirate** [comment]
Good advice, thanks. I just forgot that.
