### ISSUE TITLE
IDE tasks should be provided by a separate plugin

### ISSUE THREAD

**Issue by bmuschko** [gogradle/gogradle#126]
At the moment IDE tasks are provided by default when applying the plugin as such:

```
plugins {
    id 'com.github.blindpirate.gogradle' version '0.6.5'
}
```

Some users might never want to generate IDE-specific files and therefore do not want to use those tasks or see them in the task list. 

It's far more flexible to split this functionality into a separate plugin that can ship with the same JAR. As a user I'd apply the plugin if needed e.g. like this:

```
plugins {
    id 'com.github.blindpirate.gogradle-ide' version '0.6.5'
}
```

You can read more about the implementation approach here:

- https://guides.gradle.org/designing-gradle-plugins/#capabilities-vs-conventions
- https://guides.gradle.org/implementing-gradle-plugins/#assigning_appropriate_plugin_identifiers

I believe this task is not an IDE-related task and therefore should not be grouped with tasks like `vscode` and the like?

`showGopathGoroot - Show GOPATH and GOROOT in build.`

**Comment by blindpirate** [comment]
IDE support is removed in `0.8.0` because it's a bit hackery. Now users need to set `GOPATH` and `GOROOT` which can be displayed by `gradle showGopathGoroot`.
