### ISSUE TITLE
Standard Golang packages should not be rendered in dependencies report

### ISSUE THREAD

**Issue by bmuschko** [gogradle/gogradle#127]
The dependency report renders transitive dependencies on standard Golang packages. This is more a question or discussion than an issue. Should standard package be rendered at all? I personally think it's unnecessary as those come with the Golang runtime and are not external dependencies. If you think about it in other contexts: Following the same concept then the Java plugin would have to likely render `java.util`, `java.io` and others which it doesn't.

```
$ gradle dependencies

github.com/bmuschko/link-verifier
\-- github.com/mvdan/xurls:d315b61
    \-- golang.org/x/net:ab54850
        |-- golang.org/x/crypto:6914964
        \-- golang.org/x/text:836efe4
            \-- golang.org/x/tools:3da34b1
                |-- golang.org/x/crypto:6914964 (*)
                \-- golang.org/x/net:ab54850 (*)
```

**Comment by blindpirate** [comment]
Thanks for raising it. As far as I know, in Go, standard package is something like 'os/standard' (see [here](https://golang.org/pkg/)), which is shipped with go distributions. Package `golang.org/x` aren't standard packages (at least people won't call them standard package), they are just ordinary packages with name starting with `golang.org`. They are imported as ordinary packages and managed by VCS system so I think it's necessary to display them.
