### ISSUE TITLE
In Gradle custom task names do not add `Task`

### ISSUE THREAD

**Issue by bmuschko** [gogradle/gogradle#129]
In Gradle core task types do not include the suffix `Task`. It's implied that it _is_ task given the context. The same pattern should be applied to the tasks provided by this plugin e.g. `GoBuild` instead of `GoBuildTask`.

**Comment by blindpirate** [comment]
Thanks for reminding. I'll fix that.

**Comment by blindpirate** [comment]
I'll close this since I've already fixed it in develop branch so that I could see open issues as a checklist.
