### ISSUE TITLE
Certain task should be configurable through properties

### ISSUE THREAD

**Issue by bmuschko** [gogradle/gogradle#130]
For the `fmt` task the [documentation proposes](https://github.com/gogradle/gogradle/blob/master/docs/tasks.md#fmt) to change the options in a `doLast` action. The common pattern in Gradle is to expose properties that change the runtime behavior. A user wants to _configure_ task and not modify the runtime behavior at execution time. Exposing properties is by far the better modeling strategy here.

**Comment by blindpirate** [comment]
Good advice, thanks, I would consider it.

**Comment by blindpirate** [comment]
Will be fixed in `0.8.0`
