### ISSUE TITLE
Test task is not incremental

### ISSUE THREAD

**Issue by bmuschko** [gogradle/gogradle#131]
The `test` task provided by the plugin does not seem to define inputs and outputs. As a result the task is never up-to-date and re-executes tests even though nothing changes from a previous run.

I get the same output for every run of the task:

```
$ gradle test

> Task :test
Test for github.com/bmuschko/link-verifier/stat finished, 4 completed, 0 failed
Test for github.com/bmuschko/link-verifier/text finished, 6 completed, 0 failed
Test for github.com/bmuschko/link-verifier/http finished, 3 completed, 0 failed
Test for github.com/bmuschko/link-verifier/file finished, 6 completed, 0 failed
```

**Comment by blindpirate** [comment]
Thank you for reminding that. I should improve it in future releases.

**Comment by blindpirate** [comment]
This would shipped in `0.8.0`.

**Comment by bmuschko** [comment]
@blindpirate When are you planning to ship version 0.8.0? I think it would make sense to release more often to let users benefit from those changes.

**Comment by blindpirate** [comment]
This week or next week. Thanks for reminding.

**Comment by bmuschko** [comment]
Cool, looking forward to it. Would love to see a version this week to prep a presentation.
