### ISSUE TITLE
Global cache <some file path> doesn't match url in dependency, it will be cleared.

### ISSUE THREAD

**Issue by maguro** [gogradle/gogradle#149]
Not sure what this message means:

    Global cache /Users/adc/.gradle/go/gopath/github.com/Sirupsen/logrus doesn't match url in dependency, it will be cleared.

**Comment by blindpirate** [comment]
Previously, we keep all dependencies with same name in the same directory, which means sometimes it must be cleared to make room for other dependencies with different source. Now this behavior has been fixed in `0.8.0`. Thanks for reporting.
