### ISSUE TITLE
Build failure when using nebula.ospackage plugin

### ISSUE THREAD

**Issue by hunterford** [gogradle/gogradle#153]
I came across issue #65 when trying to debug this, because I'm having the same issue reported there. It was originally fixed in version 0.4.2, but I'm seeing this in 0.7.0.

Of course, versions are different now than they were back in April. I'm using the latest version of nebula.ospackage & gogradle.

This is all that's needed to reproduce the error (build.gradle):

```
plugins {
    id 'nebula.ospackage' version '4.5.1'
    id 'com.github.blindpirate.gogradle' version '0.7.0'
}
```

And here's the error:

```
* What went wrong:
An exception occurred applying plugin request [id: 'com.github.blindpirate.gogradle', version: '0.7.0']
> Failed to apply plugin [id 'com.github.blindpirate.gogradle']
   > Declaring custom 'build' task when using the standard Gradle lifecycle plugins is not allowed.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'com.github.blindpirate.gogradle', version: '0.7.0']
```

**Comment by blindpirate** [comment]
I think you need this: https://github.com/gogradle/gogradle/blob/master/docs/tasks.md#task-name-conflict

**Comment by hunterford** [comment]
Tracking the code, I found this: gogradle.alias=true which fixed my issue.

```
goBuild -Dgogradle.alias=true
```

**Comment by blindpirate** [comment]
Yeah was about to say. Glad to see that.
