### ISSUE TITLE
BitBucket private repos

### ISSUE THREAD

**Issue by bkrahmer** [gogradle/gogradle#160]
Hi.  I'm evaluating this plugin (which looks really promising, btw!), and ran across an issue with authentication against the bitbucket api (403 forbidden).  I know that you previously looked at this issue before, but I think the root cause was not properly identified.  I cloned your repo and hacked in an authorization header into BitbucketPackagePathResolver, and it then worked.  I would be happy to prepare a pull request to fix this issue, but would like to first know how you would suggest to handle credentials.  They need to be retrieved from somewhere.  Looking for your feedback.  thanks

**Comment by blindpirate** [comment]
Thanks for the information, could you be more specific, or say a bit more detail to let me know what happened in the credential of bitbucket?

**Comment by bkrahmer** [comment]
So I started with my first project, and was running gradle init.  I got this error:
> java.io.IOException: Error in accessing https://api.bitbucket.org/2.0/repositories/<myuser>/<private repo>, http response code: 403

I saw this in the stack trace:
at com.github.blindpirate.gogradle.util.HttpUtils.get(HttpUtils.java:49)
at com.github.blindpirate.gogradle.core.pack.BitbucketPackagePathResolver.queryByApi(BitbucketPackagePathResolver.java:77)

After looking at the code and researching, I found that a basic authorization header needed to be added.  I hacked the following code into BitbucketPackagePathResolver.java:
```
            String key = "<username>" + ":" + "<password>";
            String authHeader = "Basic " + Base64.getEncoder().encodeToString(key.getBytes());
            System.err.println("Authorization: " + authHeader);
            Map<String, String> headers = new HashMap<>();
            headers.put("Authorization", authHeader);
            String response = httpUtils.get(url, headers);
```
My suggestion would be to call httpUtils.get without the headers, and if that throws an IOException, to retry with the authentication if it's available.  To work in our environment (for local developers and on jenkins), my suggestion would be to look for the username and password as properties that would be injected into the project from the user's global gradle.properties file.  I would probably also make them settable as properties in the repositories closure in case one had to work with multiple private repos that you needed to use different credentials with.  
Thanks.

**Comment by blindpirate** [comment]
Well, I really appreciate your excellent work. However, before we do this change, I'd like you to have  a try for a simpler solution.

The reason why we need to request `https://api.bitbucket.org/2.0/repositories` is that we need to know the VCS and URL of the repository. I'm not sure if you've seen [this chapter](https://github.com/gogradle/gogradle/blob/master/docs/repository-management.md#private-repository) in documentation. I'd like to improve as you suggest if this solution doesn't work.

**Comment by bkrahmer** [comment]
Yes, I already had that closure in my gradle file.  I believe that solves a different problem, though, which is the way the native go tools work with repos.  We currently already workaround that issue by using this in our ~/.gitconfig via path rewriting:
`[url "git@bitbucket.org:<private user>/"]
    insteadOf = https://bitbucket.org/<private user>/
`

**Comment by blindpirate** [comment]
OK, let's start with why this request should be made. Let's say your package name is `bitbucket.org/my/package`, to find the code, Gogradle needs to know where this package locates (and via which tool, git or hg), so it makes request to `https://api.bitbucket.org/2.0/repositories` to fetch these information. However, if you tell Gogradle how to access this package, it wouldn't need to access this url any more, that's what [this chapter](https://github.com/gogradle/gogradle/blob/master/docs/repository-management.md#private-repository) does. Now you said you've already tried this configuration but still got this error, this makes me doubt there might be a little incorrectness in your configuration (or some bugs in my code).

Do you mind if you provides me with your repo name and your configuration in `build.gradle`? If they're too classified to be public, would you mind sending to my email `zhangbodut#gmail.com`? Thank you very much and I'd like to solve this problem with you.

**Comment by bkrahmer** [comment]
<email sent>
Bo found a misconfiguration in my regex for matching my repos.  Bo, thanks for the help!  I will now continue my evaluation and see if I can get the go guys off of their make files and back to modern technology.  :)

**Comment by blindpirate** [comment]
Glad to help! Feel free to ask whatever you like.
