### ISSUE TITLE
Failing with Gradle 4.4

### ISSUE THREAD

**Issue by kityara101** [gogradle/gogradle#164]
Hello!

Found this thing, when tried the plugin. Is it hard to fix? Want to try it :)

--------
```
admin@ubuntu:~/test/sample-comment-bch$ gradle :go-test:tasks


FAILURE: Build failed with an exception.

* Where:
Build file '/home/admin/test/sample-comment-bch/go-test/build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'com.github.blindpirate.gogradle', version: '0.7.0']
> Failed to apply plugin [id 'com.github.blindpirate.gogradle']
   > Declaring custom 'build' task when using the standard Gradle lifecycle plugins is not allowed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Comment by blindpirate** [comment]
Well, currently gogradle isn't compatible with Gradle 4.4 because it uses an internal API to render test report.  You have to use 4.3 or lower to run. New version which is compatible with `4.4` will be released in one or two weeks.

However, this error you encountered has nothing to do with `4.4` compatibility. That's due to name conflict - there's already `build` task defined in your project. See [here](https://github.com/gogradle/gogradle/blob/master/docs/tasks.md#task-name-conflict) for solution.

**Comment by kityara101** [comment]
Thanks for commenting!

Result is the same (see below). This particular _build.gradle_ does not include any other plugins. But, it is a part of a multi-project. The idea is to have a polyglot project, where golang is only one of modules. 

When I use this _build.gradle_ as a _separate project, it works_. When I use it as part of a multiproject, it does not work no matter if I specify "alias" property or no. Also, for multiprojects it is much more conventient to have same-named standard tasks like "build" and so on.

```
admin@ubuntu:~/test/sample-comment-bch/go-test$ gradle goBuild -Dgogradle.alias=true

FAILURE: Build failed with an exception.

* Where:
Build file '/home/admin/test/sample-comment-bch/go-test/build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'com.github.blindpirate.gogradle', version: '0.7.0']
> Failed to apply plugin [id 'com.github.blindpirate.gogradle']
   > Declaring custom 'build' task when using the standard Gradle lifecycle plugins is not allowed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```
This is the whole file:

```
plugins {
    id 'com.github.blindpirate.gogradle' version '0.7.0'
}

golang {
    packagePath = 'github.com/your/package' // go import path of project to be built, NOT local file system path!
}
```

**Comment by blindpirate** [comment]
Please run `./gradlew --stop` to kill all daemons.

**Comment by kityara101** [comment]
It works, thank you!
