### ISSUE TITLE
How can we provide dependency using branch name?

### ISSUE THREAD

**Issue by tajalarefin** [gogradle/gogradle#169]
If there are multiple branches in any github go project, I want to set dependency of specific branch, then how can I do it?

**Comment by tajalarefin** [comment]
I see 0.8.0 has been created. How can I use branch in the dependency? Is there any sample?

**Comment by blindpirate** [comment]
`0.8.0` is released. Please see https://github.com/gogradle/gogradle/blob/master/docs/dependency-management.md#dependency-declaration for docs.
