### ISSUE TITLE
Why should gogradle.lock file be checked into version control?

### ISSUE THREAD

**Issue by amimas** [gogradle/gogradle#170]
Hello,

I'm new to Go development. I've got a Git repository and trying to add our existing Gradle conventions and builds along with our standard CI practice to this existing repository. The repository initially included a "vendor" folder containing all the third party packages.

With the help of this plugin, I'm able to pull the dependencies during build time. Being new to Go, I'm not sure about the following scenario. I'm not reporting any "issue"; just need some help/clarification.

The guide of this project suggests not to include the `vendor` directory into the project repository, which I agree. And when I run `gradlew build`, it automatically pulls all the dependencies into the `vendor` directory.

The guide also suggests checking in `gogeadle.lock` file into the repository. What is the purpose or benefit of checking this into the source control? Doesn't this mean, I have to update 2 files anytime any of the dependencies changes (i.e. `build.gradle` and `gogradle.lock`)

On a sidenote, this repository that I inherited, already includes go dep related files (i.e.`Gopkg.toml` and `Gopkg.lock`). If I'm using this gogradle plugin, is there any point in checking in these files? Is this plugin going to start using `dep` in future for package management as that seems to be the future?

**Comment by blindpirate** [comment]
Well, as you can see, `build.gradle` contains "dependency declaration", which means it might be unstable, for example, you can declare `build 'github.com/my/dependency'` without any version info. This will change over time and you might get different build result at different time. `gogradle.lock` (that's pretty much like `Gopkg.lock`) contains commit information, which is stable and can help us to get *REPRODUCIBLE* result whenever and wherever you run the build.

WRT `dep`, it depends on you. Gogradle plugin actually consists of two parts:

- dependency management
- build support

`dep` only focuses on dependency management, so you have two choices:

- Use `dep` to manage dependencies and Gogradle to manage build
- Use Gogradle to do everything.

Currently we have no plan to use `dep` as part of Gogradle, but that's a good suggestion, I'll consider it, thank you for that.

Please let me know if I didn't make myself clear.

**Comment by amimas** [comment]
Thanks for your reply. I understand the lock file containing version/commit info, which will help getting reproducible results. But, gogradle dependency management also provides the ability to specify tag/version/commit info. If these are specified, isn't it redundant to have a `gogradle.lock` file?

**Comment by blindpirate** [comment]
Kind of yes. But another point is, dependency declarations in `build.gradle` is not structural data therefore is hard to read, especially when trying to analyze a transitive dependencies. Thanks for asking, I'll close this for now. Please feel free to reopen it.
