### ISSUE TITLE
Task alias doesn't work consistently

### ISSUE THREAD

**Issue by amimas** [gogradle/gogradle#177]
Hi,

I needed to use the `distribution` plugin provided by Gradle on the same project where I'm applying `gogradle` plugin. Basically I need to archive the output of the go build along with some loose files.

I couldn't apply the `distribution` plugin because `gogradle` creates a task named `build`. That's why I tried to specify the alias by running `gradlew goBuild -Dgogradle.alias=true` but that didn't seem to work.

I played with my `build.gradle` file; specially the `build` DSL where I specify targetPlatform and build command. Somehow I got it to work but I think there's a problem somewhere and I am having trouble reproducing the exact pattern or scenario. 

For example: now when I run `gradlew tasks`, the task list shows gogradle taks names with `go` prefix (i.e. `goBuild`, `goCheck`, `goPrepare`, etc.) even though I didn't specify `-Dgogradle.alias=true`. Earlier when I tried `gradlew tasks -Dgogradle.alas=true`, the task list wasn't showing task names with "go" prefix

Sorry for opening several issues lately.

**Comment by blindpirate** [comment]
You need `./gradlew --stop` to kill all deamons first.

**Comment by amimas** [comment]
Okay, that helped. I hadn't encounter an issue like this before.
