### ISSUE TITLE
Inconsistent cross-platform build issue

### ISSUE THREAD

**Issue by amimas** [gogradle/gogradle#179]
Hi,

I'm noticing some very odd behaviour with a project where I'm trying to apply this plugin, which has been great so far. I'm not sure if I've misconfigured anything or if this is really a bug.

The `build.gradle` configured according to the documentation in terms of applying the plugin and declaring necessary dependencies. In addition, I've added the following because I need a static binary from the build for linux platform

`build.gradle`:
```gradle
goBuild {
    targetPlatform = ['linux-amd64']

    go 'build -o .gogradle/golang-package --ldflags "-extldflags -static" golang-package'
}
```

### Build Issue
The build completes successfully on my MacOS version 10.12, but it fails to compile on a pure CentOS 7 linux with following error:

```
/root/.gradle/go/binary/1.8.1/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':golang-package:buildLinuxAmd64'.
> Build failed due to return code 2 of: 
  Command:
   /root/.gradle/go/binary/1.8.1/go/bin/go build -o .gogradle/golang-package --ldflags -extldflags -static golang-package
  Env:
   GOEXE=
   GOPATH=/root/Documents/git-repo/golang-package/.gogradle/project_gopath
   GOROOT=/root/.gradle/go/binary/1.8.1/go
   GOOS=linux
   GOARCH=amd64
```

The build is failing on my CI/CD, which is linux platform. I think some packages are missing on this linux machine. I won't have access to modify/install anything the CI/CD machines. I need to resolve this using Gradle but haven't figured out what to do about it.

#### CentOS 7
To avoid the above mentioned build issue on my centos linux machine, I've commented out the extra build command.

`build.gradle`:
```gradle
goBuild {
    targetPlatform = ['linux-amd64']

    //go 'build -o .gogradle/golang-package --ldflags "-extldflags -static" golang-package'
}
```
Now the build completes successfully and a binary is created in `.gogradle` directory named `golang-package-linux-amd64`

If I run `file golang-package-linux-amd64` on that machine, I get following info about this binary that shows it's not a statically linked binary, which is what I expected but unfortunately I need statically linked binary.

```
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=f3ef6c8ebffab3611509db20f3d10350906450f2, not stripped
```

---
##### Test 1: Building with custom command ignored (static binary)
If I run the same build script change on my Mac, I get a different result.

`build.gradle`:
```gradle
goBuild {
    targetPlatform = ['linux-amd64']

    // go 'build -o .gogradle/golang-package --ldflags "-extldflags -static" golang-package'
}
```

I get the same binary generated in `.gogradle` directory. Running `file golang-package-linux-amd64` on my Mac shows following info:

```
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

Notice that the generated binary is already statically linked even though I commented out the custom build command that is supposed to make that happen.

##### Test 2: Building with custom command included (static binary)

Now, let's uncomment that line on my Mac since I don't have previously mentioned build issue on this platform.

`build.gradle`:
```gradle
goBuild {
    targetPlatform = ['linux-amd64']

    go 'build -o .gogradle/golang-package --ldflags "-extldflags -static" golang-package'
}
```
After a clean build on my Mac, I have a newly generated binary. This time when I run `file golang-package`, I get the following output:

```
Mach-O 64-bit executable x86_64
```
This is strange. It's as if the result of `Test1` and `Test2` have switched.

##### Test3: Don't specify `targetPlatform` or custom build command

Now, my commented out all the configurations of `goBuild` DSL

`build.gradle`:
```gradle
goBuild {
    // targetPlatform = ['linux-amd64']

    // go 'build -o .gogradle/golang-package --ldflags "-extldflags -static" golang-package'
}
```
This generates a binary named `golang-package-darwin-amd64`. Running `file` command for this binary shows same result as `Test2`

##### Test4: Specify multiple platform but no custom build command

`build.gradle`:
```gradle
goBuild {
    //targetPlatform = ['linux-amd64']
    targetPlatform = ['windows-amd64', 'linux-amd64', 'linux-386']
    //go 'build -o .gogradle/kafka-log-driver --ldflags "-extldflags -static" kafka-log-driver'
}
```
This obviously produces 2 binaries. Fails to build Windows platform (I don't necessarily need it but I'm not focusing on that right now. Not sure if it has to do with codes in my package). Running `file` command on the other 2 linux binaries shows following:

```
$ file .gogradle/golang-package-linux-386 
.gogradle/golang-package-linux-386: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, not stripped

$ file .gogradle/golang-package-linux-amd64 
.gogradle/golang-package-linux-amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

The `golang-package-linux-amd64` package now seems to be a linux binary that is already statically linked. This makes sense build script change is almost same as `Test1`

---
Sorry about this looooooong description. My build was being successful on my Mac but couldn't use the generated binary to proceed to the next step. The following site helped with debugging:

https://blog.hashbangbash.com/2014/04/linking-golang-statically/

**Comment by amimas** [comment]
Hi there,

I'm just wondering if you had a chance to see this issue. In my case, the following produces 2 types of output.

```gradle
goBuild {
    targetPlatform = ['linux-amd64']
}
```

This generates an output that is different depending on the platform where the build is executed. If the build is executed on a Mac computer, the output is a binary file that is already statically linked. If the build is executed on a Linux (CentOS/RHEL), it generates a binary that is **not statically linked**.

Since I need the build output to be statically linked regardless of the platform where build is run, I need use the following as a work-around so that the build output is same on both platforms (MacOS and Linux).

```gradle
goBuild {
    targetPlatform = ['linux-amd64']

    if(org.gradle.internal.os.OperatingSystem.current().linux) {
        go 'build -o .gogradle/test-golang-package-linux-amd64 --ldflags "-extldflags -static" -tags netgo -installsuffix netgo test-golang-package'
    }
}
```
 
Could this possibly be a bug in golang?

**Comment by blindpirate** [comment]
Well, thanks for reporting, but I don't think there's much we can do on Gogradle's side. Let me first explain what's happening here.

If command line args is not specified:

```
goBuild {
}
```

Gogradle will run `go build -o .gogradle/${PROJECT_NAME}-${GOOS}-${GOARCH} ${your_package_name_declared_in_build.gradle}` by default with `GOOS`/`GOARCH` corresponding to the platform where the build happens.

Now, you add `targetPlatform`:

```
goBuild {
     targetPlatform = ['windows-amd64', 'linux-amd64', 'linux-386']
}
```

Gogradle will run the command line args 3 times with the following environment variables:

- `GOOS`=`windows`/`GOARCH`=`amd64`
- `GOOS`=`linux`/`GOARCH`=`amd64`
- `GOOS`=`linux`/`GOARCH`=`386`

Because you didn't specify a command, the default command will be executed.

Now you add one more line:

```
goBuild {
     targetPlatform = ['windows-amd64', 'linux-amd64', 'linux-386']
     go 'build -o .gogradle/test-golang-package-linux-amd64 --ldflags "-extldflags -static" -tags netgo -installsuffix netgo test-golang-package'
}
```

Gogradle will run `go 'build -o .gogradle/test-golang-package-linux-amd64 --ldflags "-extldflags -static" -tags netgo -installsuffix netgo test-golang-package'` 3 times with the following environment variables:

- `GOOS`=`windows`/`GOARCH`=`amd64`
- `GOOS`=`linux`/`GOARCH`=`amd64`
- `GOOS`=`linux`/`GOARCH`=`386`

That's all. What Gogradle does is pretty simple, fork a subprocess to run the command you provide (if you specify it) or default command with `GOOS`/`GOARCH` environment variables which is determined by `targetPlatform`. Therefore, the experiments you did can be reproduced with only go command and have nothing to do with Gogradle.

I'd suggest you to debug it with pure go command and make sure the binaries generated by `go build` command are good, then try Gogradle.

Please let me know if there's anything unclear.
