### ISSUE TITLE
Several problesm and questiond about gogradle (One build error)

### ISSUE THREAD

**Issue by klugier** [gogradle/gogradle#180]
I am just started my journey with golang and trying to create project structure using gogradle, but without luck.

My project looks like this:
-- TaskService
    -- build.gradle
    -- src
        -- main.go
    -- ... (other stuff like gradlew, gradlew.bat etc.)

My build script looks as follow:
```
plugins {
    id 'com.github.blindpirate.gogradle' version '0.8.0'
}

golang {
    // Why this is need? Without declaring packagePath I have bad null pointer exception :(
    // In the examples I see a reference to github, but currently I don't want to use any github
    // repository or package. Can anyone explain this to me?
    packagePath = 'src'
}

build.dependsOn check 

build {
    // Shouldn't targetPlatform variable be specify by default to the current machine that executes the code.
    // Currently I am working from Ubuntu, so it shouldn't be so much deal.
    // Moreover, you could write the list of platforms in the documentation. I have a luck by finding the reference to the 64 bit version of Linux in the repository.
    targetPlatform = ['linux-amd64']
    go 'build src/ -o bin/TaskService${GOEXE}'
}
```

And after running it with command:
```
./gradlew build
```

I have following error:
```
Found go 1.6.2 in /usr/bin/go, use it.
:prepare
Use project GOPATH: /home/klugier/Dokumenty/Programy/Go/TaskService/.gogradle/project_gopath
:resolveBuildDependencies UP-TO-DATE
:resolveTestDependencies UP-TO-DATE
:installDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installDependencies'.
> org.gradle.api.internal.tasks.TaskStateInternal.getOutcome()Lorg/gradle/api/internal/tasks/TaskExecutionOutcome;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.499 secs
```

Any suggestions how to fix it? Thanks and I would be grateful for the answer.

**Comment by blindpirate** [comment]
Before starting, I strongly recommend you to read [doc](https://golang.org/doc/code.html) about pacakge path. 

WRT the failure, which Gradle version are you using?

**Comment by klugier** [comment]
I use grade 2.10 that is bundle to my current distribution.

I changed the organization of the package, so it is now src/main and set the same variable to packagePath, but in this case the gradle goes into the infinite loop... 

The similar build works with MAKEFILE, so I do not see the reason why gradle shouldn't support above organization. I want to keep my sources in src directory.

Can you answer to my questions posted on the gradle script?

**Comment by blindpirate** [comment]
Gradle 2.10 is quite old, this plugin needs Gradle 3.5+. I guess I should make the error message more friendly.

`packagePath` is golang package's [import path](https://golang.org/doc/code.html#ImportPaths). What do you mean by the terminology "organization"? Seems there's no "organization" in Golang's world.

**Comment by amimas** [comment]
In my experience, if you don't specify the `targetPlatform`, gogradle will default to the current machine where the build is running and it will produce a binary for that platform.

**Comment by klugier** [comment]
I update gradle to version 4.4.1 and it seems that the ininit loop problem doesn't reproduce on that version. I highly suggest to assert against gradle version before using this plugin.

targetPlatform variable is not need for successful build.

And finally I need to change packagePath to:
```
packagePath = './src/main'
```
After that project builds without error. So, thanks for help.

**Comment by klugier** [comment]
Please close, I change my project organization a little bit and your solution works fine.

**Comment by amimas** [comment]
Would you mind sharing what you've changed in terms of "change my project organization"?

**Comment by klugier** [comment]
I moved all my sources to the workspace root directory. Previously I kept it in src/main.
