### ISSUE TITLE
Requirements and recommendations about Gogradle

### ISSUE THREAD

**Issue by JackTiger** [gogradle/gogradle#184]
使用gogradle时，我有几个需求点，麻烦评估一下，看看合不合理，是否能实现这几个功能：
1.gogradle.lock生成时，是否可以包含gosdk版本信息(go的版本)，例如go1.8/go1.9

2.gogradle.lock基于同一版本能否生成相同的文件格式，使生成具有幂等性

3.gogradle构建时，如果不同的库使用gogradle时定义了go的SDK版本，gogradle可否解析这类冲突，比如A定义了它依赖go1.8，B依赖go1.9，能否构建时解决GO sdk的冲突

4.构建中，依赖的层级比较多，比如A依赖B，B依赖C，C如果出现了Bug，当前的做法，需要修改A B C三个工程的gogradle.lock文件，逐级往上修改。我之前考虑构建时可不可以基于分支，A B C的lock文件中记录了分支信息，每次构建都取这个分支下的最新版本，这样我修改了C之后，A和B工程都不需要修改，我只需重新构建下A和B即可。

非常感谢，期待你的回复！

@blindpirate

**Comment by blindpirate** [comment]
1. 暂不考虑。

2. 现在不是幂等的么？幂等问题应该在这个PR解决掉了 https://github.com/gogradle/gogradle/pull/135

3. 暂时没有这个打算

4. 这个可以考虑在未来1~2个版本内实现

**Comment by JackTiger** [comment]
好的，谢谢！第二个问题最新版本已经解决了吗？我试一下
第四个问题，最近有版本计划吗，这个需求点对我非常重要，想尽早跟进，非常感谢！

**Comment by JackTiger** [comment]
@blindpirate

**Comment by JackTiger** [comment]
你好，是不是isLastet判断语句中返回改成返回true就可以满足每次更新先从本地缓存里查询，如果没有再从外源仓库中查找版本？
谢谢~

```
  VcsNotationDependency d = (VcsNotationDependency) dependency;
            if (d.isLatest()) {
                return true;
            } else if (d.getCommit() != null) {
                return getAccessor().findCommit(repoRoot, d.getCommit()).isPresent();
            } else if (d.getTag() != null) {
                return findMatchingTag(repoRoot, d.getTag()).isPresent();
            } else if (d.getBranch() != null) {
                // we see branch as volatile, always perform pull when a branch was specified
                return false;
            } else {
                throw new IllegalStateException("Shouldn't be here: " + dependency);
            }
```

**Comment by blindpirate** [comment]
可能没有这么简单，需要你稍微读一下代码。

**Comment by JackTiger** [comment]
使用gogradle0.8.0时，遇到一个Bug，定义依赖时使用分支构建，第一次构建成功，将全局缓存中对应下载的库删除，重新构建，报错：

```
Caused by: com.github.blindpirate.gogradle.core.exceptions.BuildException: Build failed due to return code 128 of cmd: git log feature/gogradl
e -1 --pretty=format:%H:%ct
stderr: fatal: ambiguous argument 'feature/gogradle': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

```

原因：删除后重新构建下载的为master分支下的最新代码，不是指定分支的最新代码

**Comment by blindpirate** [comment]
原因是`git clone`默认不会把`remote/origin`的分支track为本地分支的。会在下个版本解决。下个版本的发布时间现在不确定。

**Comment by blindpirate** [comment]
Fixed by `0.8.1`.
