### ISSUE TITLE
Go distribution download with default URL takes a long time

### ISSUE THREAD

**Issue by bmuschko** [gogradle/gogradle#185]
From what I can see in the documentation the URL `https://golangtc.com/static/go` is used to download a Go distribution. At times downloading the distribution is extremely slow (from the US).

The Golang download page uses a different URL (`https://redirector.gvt1.com/edgedl/go`) which might be region-based? I could download the distribution in parallel much faster from the page than from the command line. The URL on the page also provides all archived Golang versions.

Maybe the default URL should be swapped over.

**Comment by blindpirate** [comment]
Well, that's not the default url, the default is something like [`https://storage.googleapis.com/golang/go1.7.4.windows-386.zip`](https://github.com/gogradle/gogradle/blob/aa33c9964ff65b954d1a7ee74ee7ba3ff2bb0bec/src/main/java/com/github/blindpirate/gogradle/GolangPluginSetting.java#L54). That's just documenting how to change the default download url template. 

Still thanks, I'll change it to the default `googleapi` url.

**Comment by bmuschko** [comment]
I guess in that case `https://storage.googleapis.com` was really slow for me.
