### ISSUE TITLE
gogradle lock has unexpected changes

### ISSUE THREAD

**Issue by amimas** [gogradle/gogradle#200]
Hi,

I already have an existing `gogradle.lock` file generated and checked into git vcs. I need to bring a new dependency for a new feature. So, I added that new dependency in my `build.gradle` file

I took the following steps to regenerate the `gogradle.lock` file

1. Delete the existing `gogradle.lock` file
2. Run `gradlew golock`
3. New copy of `gogradle.lock` file is generated

When I look at the git diff of `gogradle.lock` file, I see the new dependency's info is added. This is expected. But, I also see 1 additional change.

```
    name: "golang.org/x/tools"
-    commit: "fbec762f837dc349b73d1eaa820552e2ad177942"
+    commit: "99037e3760ed7d9c772c980caee42b17779b80ce"
    url: "https://go.googlesource.com/tools"
    transitive: false
```

Why did this change? I don't have `golang.org/x/tools` as one of the dependencies in my `build.gradle`, but I think it's used by gogradle. However, I didn't change the version of gogradle being used. So, to me this change is unexpected and can't explain why it changed.

**Comment by blindpirate** [comment]
Is that transitive package of the package you added just now?

**Comment by amimas** [comment]
Ah... That's a good point. I forgot about transitive dependency. I will have to check the new dependency I added but I think it makes sense.

**Comment by blindpirate** [comment]
Feel free to reopen if issues still exist.
