### ISSUE TITLE
Local Cache does not update when using branch dependencies to build

### ISSUE THREAD

**Issue by JackTiger** [gogradle/gogradle#201]
构建项目A中依赖了B项目的某个分支：
[name: 'github.com/cell_sample/functionhive', branch: 'feature/gogradle']

我设置了缓存策略
golang {
  globalCacheFor(5,'seconds')
}

第一次本地构建，能够从远端获取到feature/gogradle分支下的最新版本
远端修改了feature/gogradle下的版本提交
第二次构建，无法从远端获取到feature/gogradle分支的最新版本，还是基于第一次构建的缓存记录进行构建

删除.gogradle以及.gradle后，重新构建，可以获取到最新版本。

缓存策略没有生效，麻烦帮我看一下，谢谢！

**Comment by blindpirate** [comment]
我想要知道，`resolveBuildDependencies`任务是否真正执行了，还是被标价成了`UP-TO-DATE`而没有执行。参数`--console=plain`可以将任务的执行结果打印在任务名后面。

**Comment by JackTiger** [comment]
```
$ ./gradlew gB --console=plain
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Parallel execution with configuration on demand is an incubating feature.
gogradle version is ps_go_gradle_ver-0.8.1.4
build_outputis : cell
C:\Users\l00377907\.gradle
Found go 1.8 in C:\Go\bin\go.exe, use it.
:goPrepare
Found global GOPATH: D:\progma\Go.
:resolveBuildDependencies UP-TO-DATE

```

**Comment by JackTiger** [comment]
被标价成了UP-TO-DATE而没有执行，我设置了缓存策略，这边为啥没有被执行，不是很理解，因为我远端分支更新了

**Comment by blindpirate** [comment]
这个UP-TO-DATE机制是Gradle的，Gradle无法知道你远端是否更新了。加`--refresh-dependencies`试试。

**Comment by JackTiger** [comment]
如果使用分支构建的话，那globalCacheFor(5,'seconds')缓存策略怎么生效。
我加了个临时方案：
project.tasks.resolveBuildDependencies.dependsOn(cleanBuild)

cleanBuild任务删除了.gogradle中的cache目录，执行时可以保证使用分支依赖时，每次都会去check

@blindpirate

**Comment by JackTiger** [comment]
我的这个方案感觉比较挫。
咨询下每次构建如果不指定依赖，你都会从远端获取最新代码，如果本地构建过，没有把.gogradle下的cache清除，怎么保证能从远端更新最新的代码，这个功能你那边怎么实现的？谢谢！

**Comment by blindpirate** [comment]
`--refresh-dependencies`试过了么？

**Comment by JackTiger** [comment]
我加了--refresh-dependencies 是可以的， 但是这个有些问题，你现在默认不加依赖(commit/tag/branch)是每次都从远端check是否更新的，那如果不加--refresh-dependencies，你这个功能能保证每次构建都获取最新的版本吗，我理解我现在遇到的问题跟这个场景是一致的。

```
./gradlew gB --refresh-dependencies --console=plain 
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Parallel execution with configuration on demand is an incubating feature.
gogradle version is ps_go_gradle_ver-0.8.1.4
build_outputis : cell
C:\Users\l00377907\.gradle
Found go 1.8 in C:\Go\bin\go.exe, use it.
:goPrepare
Found global GOPATH: D:\progma\Go.
:resolveBuildDependencies
Resolving code.huawei.com/cell_sample/functionhive: branch='feature/gogradle', urls=[git@code.huawei.com:cell_sample/functionhive.git]
```

@blindpirate

**Comment by blindpirate** [comment]
有点听不懂你说的话。

`UP-TO-DATE`是Gradle的机制：https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks

如果所有的东西都不改变，`ResolveDependencies`任务就不会被执行。此时任务会被标记成`UP-TO-DATE`，所有的依赖解析都不会执行。`--refresh-dependencies`可以令这个任务强制执行。

**Comment by JackTiger** [comment]
我举个例子：（摘了你的原稿，默认情况下，如果你的声明没有指定commit/tag/branch的话，Gogradle会每次执行git fetch或者hg update -u，以保证获取远端的最新版本。）

```
dependencies {
    golang {
        build 'github.com/user/project'  // No specific version, the latest will be used
    }
}
```

如果我定义了上述的依赖，那我每次构建都会从远端去获取最新的代码，那你这种情况怎么保证的？
gradle也是无法识别到远端是否发生了变更，我不知道我说清楚了没？

**Comment by blindpirate** [comment]
每次“构建”不一定会去远端获取最新的代码，每次“依赖解析”才会。

**Comment by JackTiger** [comment]
那我理解每次构建后，下次构建执行“依赖解析”会去从远端获取最新代码，那这个周期是多久呢，是你提到的globalCacheFor设置的缓存时间吗？我设置过这个参数，貌似没有生效。那这里就有个问题了，除非我手动把gradle中的缓存删除了(删除.gogradle/cache这个目录)，不然我第二次构建时永远不会执行“依赖解析”，我不知道我理解对不对？

**Comment by blindpirate** [comment]
> 我设置过这个参数，貌似没有生效。

这个“没有生效”指的是什么没有生效？

- 第二次构建应当重新解析依赖，但是没有重新解析。
- 第二次重新解析依赖应该重新从远端拉一次代码，但是没有拉。

> 除非我手动把gradle中的缓存删除了(删除.gogradle/cache这个目录)，不然我第二次构建时永远不会执行“依赖解析”

不是，`--refresh-dependencies`可以强制令“依赖解析”执行。

**Comment by JackTiger** [comment]
没有生效，指你说的第二种情况，是指我设置了缓存的时间，globalCacheFor(5, "seconds")，5秒后，我重新执行gradlew goBuild， 没有执行依赖解析，还使用的之前的缓存去构建。

dependencies {
    golang {
        build 'github.com/user/project'  // No specific version, the latest will be used
    }
}

**Comment by JackTiger** [comment]
你说的第一种情况，是依赖定义发生了变更，比如我重新定义了commit/tag，这个当前是OK的。

第二种情况，是我的依赖定义没有发生变更，这种情况下，我设置了缓存的时间，缓存时间后，我重新构建，不使用--refresh-dependencies的情况，是无法从远端去拉取 代码的。

**Comment by blindpirate** [comment]
没有重新执行依赖解析是第一种情况，到底是哪一种？如果没有重新执行依赖解析，那就是预料之中的，需要使用`--refresh-dependencies`强制重新解析依赖。

**Comment by JackTiger** [comment]
你的意思是我构建时必须使用--refresh-dependencies强制刷新，触发“依赖解析”执行，那globalCacheFor(5, "seconds")这个参数主要的功能是做什么的？

我之前理解，你这个参数是用来控制本地缓存的生命周期的，如果本地缓存代码超过了这个缓存时间，你就会自动从远端获取新的代码执行构建

**Comment by blindpirate** [comment]
缓存时间指的是"超出这个时间后，依赖解析会重新询问远端"，而不是“超出这个时间后，下次构建会重新进行依赖解析”。

**Comment by JackTiger** [comment]
你的意思是，超出缓存时间后，依赖解析会重新询问远端，但是依赖解析的触发不是它来控制的，而是gradle本身。那如果本地gradle依赖没有变化，我这边只能使用--refresh-dependencies的方式来强制触发依赖解析了？

**Comment by blindpirate** [comment]
是的。

**Comment by JackTiger** [comment]
那我这边的场景使用就有些困难了，我使用branch，就是想每次都从远端去更新分支下的最新代码，但是有些库，比如没有指定tag/branch/commit的，我想每次都基于本地缓存中已有的代码构建。我目前想到的比较挫的方式是把.gogradle下的cache删除，重新构建。

**Comment by blindpirate** [comment]
和`--refresh-depedencies`等价的参数有`-Dgogradle.refresh=true`，可以把这个参数持久化在`gradle.properties`里。当然你可以fork一份代码随意修改。

**Comment by JackTiger** [comment]
以你的经验，这里有办法在代码里控制吗，比如说我定义了分支依赖，构建时gradle文件没有变更，只Check分支依赖的这类情况，让它只check远端分支有没有更新，其他的不去check，可以做到吗？

**Comment by blindpirate** [comment]
代码当然可以控制，但是我觉得没有必要去做。如果你有需要的话当然可以自己修改。

**Comment by JackTiger** [comment]
代码控制，在哪个里面做，可以给个建议吗，我这边的服务对构建时长有要求

**Comment by blindpirate** [comment]
https://github.com/gogradle/gogradle/blob/master/src/main/java/com/github/blindpirate/gogradle/task/ResolveDependencies.java#L89

现在“在build.gradle”中定义的依赖是`ResolveDependency`任务的一个input，所以你需要有条件地令这个input失效，从而令依赖解析任务执行。

**Comment by JackTiger** [comment]
你说的失效，我没理解是什么意思，，如果check到当前的依赖是基于分支的，每次强制更新分支的依赖，我就想完成这个功能

```
    public HashSet<GolangDependency> getDependencies() {
        setGogradleGlobalContext();
        GolangConfiguration configuration = configurationManager.getByName(getConfigurationName());
        configuration.resolveFirstLevelDependencies();
        // elements in GolangDependency are identified by name, here we want to identify them by equals
        return new HashSet<>(configuration.getDependencies());
    }
```

你这一段直接返回了一个HashSet的对象，你说的失效，是指这里返回nil??

**Comment by blindpirate** [comment]
我十分建议你先阅读一下这份文档：https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks

**Comment by JackTiger** [comment]
谢谢，我刚看了这个文档，增量构建的输入和输出，只要让输入变更，就可以，你刚提到的“在build.gradle”中定义的依赖是ResolveDependency任务的一个input，那么按你的建议，只要这个输入在你的代码段里变更一下，就可以了，是吧

**Comment by JackTiger** [comment]
咨询下，最近我在执行构建任务时，偶现installDependencies failed，你那边有遇到过吗？

```
:installDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installDependencies'.
> java.io.IOException: Unable to delete directory E:\code\go\gopath\src\code.xxxxx.com\xxxx\xxxxx\vendor\github.com\grpc-ecosystem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by blindpirate** [comment]
检查`getDependencies()`返回的每个dependency，如果有branch信息，那么就返回一个和上次不同的`HashSet`，令Gradle认为输入改变而重新执行此任务。例如，当`--refresh-dependencies`开启的时候，`getRefreshDependenciesFlag()`会返回一个随机数： 

https://github.com/gogradle/gogradle/blob/8e26e3e475f85e370989e7db25f0a6d0d387ed00/src/main/java/com/github/blindpirate/gogradle/task/ResolveDependencies.java#L123

**Comment by blindpirate** [comment]
这种`IOException`问题多见于windows，windows不允许两个进程同时访问一个文件，我很少用所以没遇到过。

**Comment by JackTiger** [comment]
`检查getDependencies()返回的每个dependency，如果有branch信息，那么就返回一个和上次不同的HashSet，令Gradle认为输入改变而重新执行此任务。例如，当--refresh-dependencies开启的时候，getRefreshDependenciesFlag()会返回一个随机数：`

谢谢你的建议，我尝试一下，加了这个方法后，只会对有分支的依赖进行检查吗，其他使用tag/commit定义的依赖会重新检查吗？

我理解你是把定义的整个依赖作为输入，所以按照你说的方法，输入改了，整个定义的依赖都会重新解析，不管是branch或者tag/commit。

**Comment by blindpirate** [comment]
是的，但是tag/commit会从缓存读数据，不会和远端通信。

**Comment by JackTiger** [comment]
那我理解是不是和运行时加这个参数--refresh-dependencies是一样的功能，只不会把刷新这个功能放到了gogradle插件中。

**Comment by blindpirate** [comment]
是的，看来是我误解了你的意思。“依赖解析”是一个完整的过程，要么全解析（包括从缓存解析），要么不解析，不能只解析一部分，至少现在的架构没有提供这个可行性。

**Comment by JackTiger** [comment]
好的，谢谢，了解了~

**Comment by JackTiger** [comment]
咨询两个小问题：
1.--refresh-dependencies会触发强制执行ResolveDependency，那么对于构建项目中的依赖，只是指定了branch或者没有指定任何版本信息的库，会强制和远端通讯，那么对于传递性依赖(传递性依赖中定义了gogradle.lock或者其他版本锁文件)中得到的依赖，会强制刷新传递性依赖中的版本吗？

2.globalCacheFor(5, "seconds")这个参数，我如果使用--refresh-dependencies的方式，是不是globalCacheFor这个参数的设置可以忽略了

**Comment by blindpirate** [comment]
1.取决于锁文件锁的是什么，锁的是commit就不会和远端通信，锁的是branch就会和远端通信。不懂“刷新传递性依赖中的版本”这个术语是什么意思。

2.这个参数的意义和使用方法详见上文。是否使用这个参数，忽略不忽略，取决于你自己的需求，由你自己来决定，你应当比我更了解你自己的需求。

**Comment by JackTiger** [comment]
第一点我的意思是，A->B，A依赖B，B中有版本锁文件(gogradle.lock或者其他版本锁)， 那么我构建A时，使用--refresh-dependencies会不会对B中锁定的版本也和远端进行通讯，去更新B中依赖版本

**Comment by blindpirate** [comment]
> 取决于锁文件锁的是什么，锁的是commit就不会和远端通信，锁的是branch就会和远端通信。

**Comment by JackTiger** [comment]
你的最新版本支持锁定branch了？？我试试，如果可以支持锁定branch，那我之前提的需求，跨级依赖分支的功能也就支持了，NB！

**Comment by JackTiger** [comment]
我刚试了下goLock任务，执行成功后，不会锁定branch，还是锁定commit?  这样的话传递性依赖怎么处理分支依赖的情况呢，当前对于传递性依赖的获取只会检查版本锁文件/vendor/源码

**Comment by blindpirate** [comment]
`gogradle.lock`不支持锁定branch，但是有些外部工具支持，比如gopm。
