### ISSUE TITLE
Task for coverage report should respond with total coverage info

### ISSUE THREAD

**Issue by amimas** [gogradle/gogradle#203]
Feature request:

Currently when the 'test' task is executed, a nice html report is generated similar to junit type test reports. In addition, the task also prints to stdout a summary. For example:
    "10 test completed, 0 failed"

When the 'cover' task is executed, it also generates an html report about code coverage. However, there's no feedback on the stdout. One must open the generated html report to see the coverage info. Similar to 'test' task, it'd be nice to have an immidiate feedback on the terminal about summary/total percentage of the code covered. For example:
    "Total test coverage 83%"

This is useful info when running the task that generates detailed coverage report. It can also be useful by CI/CD. For example, Gitlab CI can parse the log and capture the coverage info, which then can be displayed in a pull/merge request. Gitlab CI can also generate a coverage badge that can be included in project's readme.

https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-report-badge

https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing

**Comment by blindpirate** [comment]
Closed by `0.9`. Thanks for reporting!
