### ISSUE TITLE
github-rank Link is broken ...

### ISSUE THREAD

**Issue by CodeFreezr** [gogradle/gogradle#204]
Hello,

after navigate to the github-rank on your readme.md I see only this:

"The owner of github-rank.com is offering it for sale for an asking price of 877 USD!"

Can't see Top1000 Golang Projects ...

**Comment by blindpirate** [comment]
Thanks. Already updated to https://github.com/search?l=&o=desc&q=stars%3A%3E1+language%3AGo&ref=advsearch&s=stars&type=Repositories&utf8=%E2%9C%93
