### ISSUE TITLE
Updating gogradle.lock

### ISSUE THREAD

**Issue by sapei** [gogradle/gogradle#206]
Let's say I have defined two depencies, e.g..: github.com/golang/protobuf and google.golang.org/grpc, in the build.gradle. I locked both dependencies and a gogradle.lock file was generated. 

Afterwards, I deleted the dependency to github.com/golang/protobuf and google.golang.org/grpc in the build.gradle. I would like to update the gogradle.lock by executing the task 'lock' again. However the gogradle.lock was not updated even though the task 'lock' has been executed. The file gogradle.lock must be first removed to create a new one. By doing this, the git commit hash for some transitive dependencies in the new gogradle.lock will be different with the old one. Therefore the build is not reproducible anymore. 

Is there a mechanism to update the gogradle.lock when the dependencies in build.gradle have been modified?

**Comment by blindpirate** [comment]
Thanks for reporting, could you try to run with `-Dgogradle.mode=DEV`?

https://github.com/gogradle/gogradle/blob/c936042b13cdc87fea315978e37debbc0127a851/docs/getting-started.md#resolve-dependencies-and-install-them-into-vendor

**Comment by blindpirate** [comment]
Close due to unresponsiveness.
