### ISSUE TITLE
ResolveDependencies Task Can not get dependencies from transitivity gogradle.lock file

### ISSUE THREAD

**Issue by JackTiger** [gogradle/gogradle#210]
gogradle使用版本：0.8.1

问题场景：
1.定义了两个git仓库：
github.com/JackTiger/dcf
github.com/JackTiger/dcfcomm

github.com/JackTiger/dcf依赖github.com/JackTiger/dcfcomm，使用gogradle编译后，生成lock文件上传

2.在另外的仓库github.com/JackTiger/dcftest中依赖了github.com/JackTiger/dcf
在github.com/JackTiger/dcftest仓库中执行构建

问题：
github.com/JackTiger/dcftest构建完成后，vendor中只有dcf，没有dcfcomm这个库

```
vendor/
   github.com/JackTiger/dcf
```

怀疑结果：
分析了日志，没有找到对github.com/JackTiger/dcfcomm这个库的解析

**Comment by JackTiger** [comment]
我按照我的场景定义了demo
https://github.com/JackTiger/dcf库中的gogradle.lock依赖了https://github.com/JackTiger/dcfcomm这个库

你在你自己的仓库中直接依赖github.com/JackTiger/dcf这个库，构建完成，发现vendor里只有dcf，没有dcfcomm这个库

**Comment by blindpirate** [comment]
感谢报告。原因是在获取包A的传递性依赖时会排除掉包A本身，判断方法是`transitivePackage.startsWith(packageBeingResolved)`. 对于你的这个情况，`https://github.com/JackTiger/dcfcomm`刚好以`https://github.com/JackTiger/dcf`开头，所以被错误的排除掉了。很低级的错误，会在0.9里面修掉。0.9正在做最后的集成测试，本周末会发布。

**Comment by JackTiger** [comment]
好的，
0.9版本会解决下面的两个问题吗？
1.依赖包解析耗时比较长的问题，这个版本里有解决吗？之前提过，一个是网络IO，一个是Git操作
2.0.9版本有支持branch的跨层依赖吗？(之前跟你提过issue)，即
A->B->C
A依赖B的分支featureB
B依赖C的分支featureC

C中分支发生变更后，不需要修改B的版本，只需在A构建时刷新下branch版本即可

**Comment by JackTiger** [comment]
另外咨询个问题:

我在vendor里放了go.uber.org/zap这个库，但是没有放任何版本信息，gogradle在解析到这个vendor时会分析go.uber.org以及go.uber.org/zap，我有方法可以提前让gogradle识别某些包结构吗？

我尝试使用下面的方法：
```
  golang {
    root ‘go.uber.org’
    emptyDir()
  }
```
把go.uber.org/zap这个包也过滤掉了，有好的建议吗？

**Comment by blindpirate** [comment]
没听懂问题。`https://go.uber.org/zap?go-get=1`指定了根路径`<meta name="go-import" content="go.uber.org/zap git https://github.com/uber-go/zap">`，所以Gogradle会把`go.uber.org/zap`当做一个包来处理，而不会把`go.uber.org`当做一个包来处理。按照我的理解无需任何配置。

> 我有方法可以提前让gogradle识别某些包结构吗？

不明白你的意思。识别“某些“是哪些？怎么个识别法？

**Comment by JackTiger** [comment]
go.uber.org/zap放在了我的vendor里，gogradle解析时，需要判断包的结构，所以gogradle会一级一级的去判断，首先判断go.uber.org是不是一个包，其次判断go.uber.org/zap是不是一个包，这两次都需要和远端通信，我的意思可不可以我直接高速gogradle，go.uber.org不是一个包结构，不需要去判断。


即：
在查找仓库A的传递性依赖的时候，会扫描vendor并将vendor作为它的传递性依赖，对于golang.org包仍然要和远端通信，但这个通信只是为了确定vendor目录后代的包结构，即golang.org是一个包，还是golang.org/x是一个包，还是golang.org/x/tools是一个包？但是不会去执行git操作。

在上述过程中，我能否提前设定golang.org不是一个包结构，把这个信息告诉gogradle，这样会忽略对golang.org的通信检查。


另外，提个小的诉求，依赖分析以及installdependencies时的git操作可以加速或者并行处理吗，我们这边的依赖库比较多，这块比较耗时，之前也给你提过这个问题。

**Comment by blindpirate** [comment]
```
golang {
     incomplete 'go.uber.org'
}

golang {
     root 'go.uber.org/zap'
     url 'https://github.com/uber-go/zap.git'
}
```

并行是个很麻烦的问题，暂时还没考虑。

**Comment by JackTiger** [comment]
@blindpirate 
transitivePackage.startsWith(packageBeingResolved)

这段代码，在你的哪个文件里，貌似没有搜到(0.8.1版本)， 谢谢！

**Comment by blindpirate** [comment]
https://github.com/gogradle/gogradle/blob/46ddb0cfd0a12a892915a8dc0ebc22b2abeff68e/src/main/java/com/github/blindpirate/gogradle/core/dependency/produce/ExternalDependencyFactory.java#L88
