### ISSUE TITLE
Git core.symlinks=true caused circular resolution etcd package

### ISSUE THREAD

**Issue by JackTiger** [gogradle/gogradle#216]
问题描述:

git的符号链接打开时，解析etcd库 `https://github.com/coreos/etcd/blob/v3.2.10/cmd/etcdctl`

问题结果:
执行installDependencies任务时会循环拷贝这个库，导致这个任务构建时间非常长。

**Comment by blindpirate** [comment]
etc库里有这个烦人的符号链接的问题我知道，如果我没理解错的话，现在你的问题是，

如果`core.symlinks=true`，那么执行的某些git操作永远不会返回，对么？

**Comment by JackTiger** [comment]
@blindpirate 你好，请教一个问题，我这边打算使用gogradle只解析内源的库，过滤所有非内源的库，例如:

定义了如下依赖：
```
           [name: 'code.xxxx.com/xxxxx/xxxxx', tag: '0.8.0'],
            [name: 'github.com/pkg/errors'],
```

我使用gogradle分析这个依赖时，只分析code.xxxx.com/xxxxx/xxxxx它的依赖关系，对于github.com/pkg/errors以及code.xxxx.com/xxxxx/xxxxx的后代依赖，如果存在非内源的库，我想直接在gogradle过滤掉对这块的依赖解析分析，在gogradle中可以实现这个功能吗？期待你的建议，谢谢！

**Comment by blindpirate** [comment]
> 内源的库

什么是内源库？所有的以`code.xxx.com`开头的库？

> 如果存在非内源的库，我想直接在gogradle过滤掉对这块的依赖解析分析

意思是要把所有“非内源库”节点从整个依赖树中剪掉么？

**Comment by JackTiger** [comment]
“跳过依赖分析”的意思是说，这个库本身还应当被复制到vendor中，但是它不产生任何后代，是么？

是指，包括它自己以及它的后代，使用gogradle时都不去做依赖分析，直接忽略这块非内源库

**Comment by blindpirate** [comment]
我了解了。我恐怕不会实现这样的功能，若有实际需求需要你们自己实现。

**Comment by JackTiger** [comment]
@blindpirate 我可以自己实现，这块主要涉及的模块是哪些，想咨询下你这边的建议，谢谢！

**Comment by blindpirate** [comment]
请搜索ResolveContext.produceTransitiveDependencies方法

**Comment by JackTiger** [comment]
好的，感谢支持！
再咨询两个问题：
1.新版本啥时候发布？(解决依赖顺序的问题)
2.etct库里有这个烦人的符号链接的问题，是否可以通过设置core.symlinks=false解决！

**Comment by JackTiger** [comment]
@blindpirate 你好，之前咨询过你，如果使用gogradle忽略所有以github.com开头的依赖解析，在ResolveContext.produceTransitiveDependencies这个方法貌似可以忽略间接传递性依赖，但是无法忽略构建项目的直接依赖。

如果直接从当前项目的直接依赖包括间接依赖中(即所有依赖中)忽略所有以github.com开头的依赖解析，主要是在哪个方法中实现？非常感谢！

**Comment by blindpirate** [comment]
produceTransitiveDependencies产生一切依赖，包括你所说的“直接依赖”和“间接传递性依赖”， 因为“直接依赖”实际上就是项目本身的“间接传递性依赖”。

**Comment by JackTiger** [comment]
我本地demo,  produceTransitiveDependencies这个方法并不能完全屏蔽开源库，
https://github.com/gogradle/gogradle/blob/master/src/main/java/com/github/blindpirate/gogradle/core/dependency/resolve/AbstractVcsDependencyManager.java#L113  resolveRepository这个方法还是会被调用，这两者的关系是什么？

我的初衷是想在gogradle整个解析一切依赖的入口处，屏蔽开源库

**Comment by blindpirate** [comment]
> 我本地demo, produceTransitiveDependencies这个方法并不能完全屏蔽开源库

你本地demo做了什么？你没有贴出来我看不到。

> 我的初衷是想在gogradle整个解析一切依赖的入口处，屏蔽开源库，即第三方库在整个gogradle中的resolveBuildDependencies或者resolveTestDependencies中都不会去下载以及分析依赖(包括它自己以及传递性依赖)

`produceTransitiveDependencies`方法是给定一个已经解析过的包，生成它的所有直接传递性依赖（但不解析）。按照我的理解，你只需要在这个返回值中过滤掉你不想要的包就行了。
