### ISSUE TITLE
Cannot recognize package: golang.org/x/tools/go/loader

### ISSUE THREAD

**Issue by china-muwenbo** [gogradle/gogradle#219]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':resolveBuildDependencies'.
> Exception in resolution, message is:
  Cannot recognize package: golang.org/x/tools/go/loader
  Resolution stack is:
  +- github.com/my/package
   +- github.com/golang/example#0dea2d0bf90754ffa40e0cb2f23b638f3e3d7e09

I just run  typical-build   in examples    with  “./gradlew build ”？？？？？？？？？？？？？？？？

**Comment by blindpirate** [comment]
Can you paste the full stacktrace with `-s`? 

Also note that `golang.org` is blocked by GFW.

**Comment by china-muwenbo** [comment]
yes   it is blocked by GFW.........................................................

**Comment by blindpirate** [comment]
Sorry there's nothing I can help.
