### ISSUE TITLE
Gogradle support filter test package?

### ISSUE THREAD

**Issue by JackTiger** [gogradle/gogradle#223]
gogradle goTest任务支持过滤测试包吗？

比如工程中有github.com/package/sub/A， github.com/package/sub/B, github.com/package/sub/C三个测试包

执行gradlew goTest任务时，可以忽略github.com/package/sub/A这个包，只执行github.com/package/sub/B, github.com/package/sub/C两个包的测试。

谢谢！

**Comment by blindpirate** [comment]
试试这里？https://github.com/gogradle/gogradle/blob/master/docs/getting-started-cn.md#%E6%B5%8B%E8%AF%95go%E9%A1%B9%E7%9B%AE
