### ISSUE TITLE
Gradle build is suddenly failing even though the same version of the plugin worked before

### ISSUE THREAD

**Issue by amimas** [gogradle/gogradle#237]
Hello,

I'm experiencing some unexpected issues with the build of a project where I have this plugin applied for several months now. I have a problem similar to #164 

I'm running Gradle 4.4 with version 0.8.0 of this plugin. The project has been building successfully all this time and the last successful build was about a month ago. As of yesterday, the project is failing to build and keep throwing the following error message, even though there has been **no changes** to Gradle version, build script code, or this plugin's version.

```
* What went wrong:
An exception occurred applying plugin request [id: 'com.github.blindpirate.gogradle', version: '0.8.0']
> Failed to apply plugin [id 'com.github.blindpirate.gogradle']
   > Declaring custom 'build' task when using the standard Gradle lifecycle plugins is not allowed.
```

Has there been any changes to this version of the plugin (0.8.0) recently?

To make matters even more confusing, the build is failing on all the CI build servers, which are RedHat Linux based machines. However, on my Mac I am able to run the build successfully using the same Gradle Wrapper from that project that is used by the CI build servers.

**Comment by amimas** [comment]
Finally found out why I ran into this issue. The project has a `gradle.properties` file that contained `org.gradle.jvmargs` property for setting alias for the task names of the gogradle plugin.

The CI build servers had recently changed. The build servers now has a global `gradle.properties` file that contains the same property (`org.gradle.jvmargs`). As a result, Gradle build was using values defined in the global properties file, which means the task name alias for this plugin was not being set. And because of that there were multiple tasks named build and Gradle started to complain.

Can the task names be handled differently? For example, if you already applied `java` plugin, it will automatically apply a task named **build**. If you then apply `groovy` plugin, you don't need to provide any alias for the task names involving `groovy` plugin. There's no task name collision.

Or... the easiest might be to use the task name alias by default. If anyone already has a task named `build`, they can simply add a dependency on `goBuild` task.

**Comment by blindpirate** [comment]
> Can the task names be handled differently?

I'm afraid that is tough. If gogradle plugin detects other plugin's application and does auto-rename work, the following script:

```
apply plugin: "java"
apply plugin: "gogradle"
```

would succeed (with `goBuild` task created), but

```
apply plugin: "gogradle"
apply plugin: "java"
```

would fail. This doesn't look good, because the correct behavior depends on the order of plugin application.

For the issue you've encountered, I'd suggest that task renaming should always be enabled - that's what it's designed for.

**Comment by oesolutions** [comment]
@blindpirate I haven't looked too closely at this plugin's source, but is there a reason the plugin needs to create these standard lifecycle tasks? Why not just apply Gradle's 'base' plugin from this plugin's apply method?

**Comment by amimas** [comment]
I agree that using the `base` plugin sounds like the right thung to do. But this is still documented as Gradle's private API.

https://docs.gradle.org/current/userguide/standard_plugins.html#sec:base_plugins

Aside from that, it might be good to have a `go-base` plugin similar to other language specific base plugin. On top of that, this plugin can be added. Not sure if that over complicates it but that seems to be the convention followed by plugins from gradle.
