### ISSUE TITLE
Change golang distribution url?

### ISSUE THREAD

**Issue by gotson** [gogradle/gogradle#241]
Hello, i see in the file https://github.com/gogradle/gogradle/blob/78a45f70b39e887423c9ef42c37467cc433605a7/src/main/java/com/github/blindpirate/gogradle/GolangPluginSetting.java that the golang binaries are retrieved from the official repo.

At work we are running builds from Jenkins instances which don't have access to the public internet for security reasons, but we use Nexus repositories to proxy external repositories (for Maven, Nuget, npm...).

Would it be possible to have a property to point to a different url root to download the golang distribution?

For instance we are already doing that kind of thing to download Gradle binaries, using the [`distributionUrl` of the wrapper task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.wrapper.Wrapper.html#org.gradle.api.tasks.wrapper.Wrapper:distributionUrl).

**Comment by blindpirate** [comment]
@gotson You probably can configure it here: https://github.com/gogradle/gogradle/blob/78a45f70b39e887423c9ef42c37467cc433605a7/src/main/java/com/github/blindpirate/gogradle/GolangPluginSetting.java#L175

**Comment by blindpirate** [comment]
```
golang {
     goBinaryDownloadTemplate == 'http://example.com/go${version}.${os}-${arch}${extension}'
}
```

See [here](https://github.com/gogradle/gogradle/blob/master/src/test/groovy/com/github/blindpirate/gogradle/GolangPluginSettingTest.groovy#L139) for more examples.
