### ISSUE TITLE
Resolve dependencies from Vendor folder

### ISSUE THREAD

**Issue by velumaniduraisamy** [gogradle/gogradle#248]
Hi,
In my project, I have build dependencies which are in private repository for which build machines don't have access. 

I want all those dependencies to be resolved from vendor folder. So I committed vendor folder and lock fail. but resolveBuildDependencies task fails 

**Error log**
Use project GOPATH: /go/src/service/.gogradle/project_gopath
:resolveBuildDependencies
Resolving cloud.google.com/go: commit='e0c17b1c932efccf9d30ca4beca8bcf215ea7762', urls=[https://code.googlesource.com/gocloud]
Resolving contrib.go.opencensus.io/exporter/stackdriver: commit='d1e19f5c23e955d7b65ff59e935007a2edce045e', urls=[https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver]
Resolving go.opencensus.io: commit='572ae0b6fd8649e8c977bf23283f20b8beb607ce', urls=[https://github.com/census-instrumentation/opencensus-go]
:resolveBuildDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':resolveBuildDependencies'.
> Exception in resolution, message is:
  Cannot resolve dependency:github.com/MyRepo/go-orm: commit='00a3de42031842c73ec29bd5ed6bb1a182047058', urls=[https://github.com/MyRepo/go-orm.git, git@github.com:MyRepo/go-orm.git]
  Resolution stack is:
  +- project-my-sample

Could you please suggest?

**Comment by blindpirate** [comment]
IIUC, you want some dependencies stay in `vendor` and don't want gogradle to manage these dependencies. Currently gogradle sees `vendor` as a temp workspace and overwrites it with the calculated dependencies so you can't keep them there. Maybe you can put them in other directory and use `dir` declaration?

```
dependencies {
    golang {
        build name: 'a/local/package', dir: 'path/to/local/package' // It must be absolute
    }
}
```

https://github.com/gogradle/gogradle/blob/master/docs/dependency-management.md#dependency-declaration

**Comment by velumaniduraisamy** [comment]
Thank you @blindpirate.
