### ISSUE TITLE
Custom Test Case Report Format and Vendor JSON

### ISSUE THREAD

**Issue by mayur9991** [gogradle/gogradle#250]
Hello,

I want to integrate Sonarqube and Snyk.io for code quality and dependency check for my Go Project.

**Sonarqube Requirement**
With gogradle, we are only getting test case report in HTML format. Is that a way to get it in json format required by sonarqube ?
Refer : https://docs.sonarqube.org/display/PLUG/Unit+Tests+Results+Import

**Snyk.io for Dependency Check**
To do dependency scan with snyk.io, it requires Gopkg.lock or vendor/vendor.json. 
gogradle generates dependencies in its own format of gogradle.lock. How to generate lock files required by snyk ?
https://snyk.io/docs/snyk-for-golang

Regards,
Mayur

**Comment by mayur9991** [comment]
@blindpirate do you have any idea about this ?

**Comment by blindpirate** [comment]
Ah, sorry for the delay. No out-of-box solution. At the time I started to write gogradle, `go test -json` was not available - I had to parse standard output from `go test` output. I'm considering reading JSON results from Go 1.10 (if my memory is correct) but haven't finished yet. Maybe I can put the result json somewhere during the test process.

If you really want json output, you have to write some custom task, for example iterate on the go packages and run `go test -json` manually.

**Comment by mayur9991** [comment]
Ahha, Thanks for the update.

What about Gopkg.lock or vendor/vendor.json which is required for third party component scanning ?

**Comment by blindpirate** [comment]
> What about Gopkg.lock or vendor/vendor.json which is required for third party component scanning ?

I'm sorry I don't quite understand this question, can you please elaborate on it?

**Comment by mayur9991** [comment]
To do third party component scanning using tools like [Snyk.io](https://snyk.io/docs/snyk-for-golang), we need to generate Gopkg.lock or vendor/vendor.json file (refer : https://github.com/golang/dep).

Currently gogradle generates it's own gogradle.lock file which is not supported by any of these tool. 

Is there a way to generate this file with gogradle ?

**Comment by blindpirate** [comment]
Unfortunately no... gogradle is not popular enough to make others support it... you have to write an adapter to convert gogradle.lock to other files. :-(

**Comment by mayur9991** [comment]
Okay, Thanks @blindpirate.
