### ISSUE TITLE
does packagePath is necessary?

### ISSUE THREAD

**Issue by shaocongliang** [gogradle/gogradle#253]
```gradle
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath "cz.alenkacz:gradle-scalafmt:${gradle.scalafmt.version}"
  }
}

plugins {
    id 'com.github.blindpirate.gogradle' version '0.8.1'
}

subprojects {
  apply plugin: 'scalafmt'
  scalafmt.configFilePath = gradle.scalafmt.config
}

golang {
    packagePath = 'my-company/foo' as String
    buildTags = (rootProject.findProperty('goTags')?:'').split(',')
}
```
I want to build my project named foo and I ensure all dependencies are download to the vendor directory on foo.
from what I understand "packagePath" is the remote path of my project, this is right? this is necessary? 
PS: if u can't understand what i am saying place contact me by my mail(click my profile), we can talk in Chinese.

**Comment by blindpirate** [comment]
> An import path is the string with which users import a package. It specifies the directory (relative to $GOROOT/src/pkg or $GOPATH/src ) in which the package's source code resides.

That's what `packagePath` is. It's necessary since all go code must have import path.

BTW in `packagePath = 'my-company/foo' as String`, `as String` is unnecessary, and `rootProject.findProperty('goTags')?:''` is wrong.
