### ISSUE TITLE
以下是我工程目录，其中包含多个子项目，我可以使用gogradle统一管理吗？

### ISSUE THREAD

**Issue by duanlizhi** [gogradle/gogradle#266]
![image](https://user-images.githubusercontent.com/15800162/48883349-5ed0a700-ee5a-11e8-945c-f51775be21af.png)
如果可以，脚本中的packagePath应该怎么设置呢？

**Comment by blindpirate** [comment]
什么叫做“统一管理”？

**Comment by duanlizhi** [comment]
> 什么叫做“统一管理”？

我的根目录是xcjgo，src中的每一个都是可能有依赖关系的子目录，就是这些都是用一个版本依赖，你看我上面的截图中将脚本和gradlew放到了xcjgo目录下，这样构建对吗？build.gradle中packagePath这个导入路径该怎么定义呢？

**Comment by duanlizhi** [comment]
> 什么叫做“统一管理”？

我这么想对吗？

**Comment by blindpirate** [comment]
我非常推荐你先阅读一下go语言中的[import path](https://golang.org/doc/code.html#ImportPaths)的定义，然后再决定自己的项目结构。

build.gradle中packagePath就是你的项目的`import path`。

> 这样构建对吗

对不对取决于你自己想要如何构建。我现在完全不明白你的意图。

**Comment by duanlizhi** [comment]
> 我非常推荐你先阅读一下go语言中的[import path](https://golang.org/doc/code.html#ImportPaths)的定义，然后再决定自己的项目结构。
> 
> build.gradle中packagePath就是你的项目的`import path`。
> 
> > 这样构建对吗
> 
> 对不对取决于你自己想要如何构建。我现在完全不明白你的意图。

谢谢
