### ISSUE TITLE
When I Run GoGradle tasks in arm64 env, I find the llt path is not is .gogradle/reports, the report is in ~/.gradle/daemon/4.4/.gogradle/reports

### ISSUE THREAD

**Issue by JackTiger** [gogradle/gogradle#292]
When I Run GoGradle tasks in arm64 env, I find the llt result path is not is .gogradle/reports, the report is in ~/.gradle/daemon/4.4/.gogradle/reports.

The relative  path is below ~/.gradle/daemon/4.4/ not the project root directory.

**Comment by blindpirate** [comment]
> Run GoGradle tasks

Which task? How did write the task definition?

What's gogradle plugin version? It would be great if you can provide a reproducible sample. Or at least how you wrote your build script/invoked the build.

**Comment by JackTiger** [comment]
使用gogradle的最新版本都有类似的问题：
执行环境，arm64

```
自定义任务：
def generateScripts() {
  def folder = new File(".gogradle")
  if( !folder.exists() ) {
    folder.mkdirs()
  }

  def file = new File(".gogradle/test.sh")
  if (file.exists()) {
    file.delete()
  }

  def content = """#!/bin/bash
pwd
"""

    file.withPrintWriter { printWriter ->
      printWriter.println(content)
    }
}

 task testDemo()  {
        doLast {
            generateScripts()
            exec {
                commandLine "bash", ".gogradle/test.sh"
            }
        }

执行命令：
./gradlew testDemo

```
提示如下错误：
```

 .gogradle/test.sh: No such file or directory
 FAILED

FAILURE: Build failed with an exception.

```

查看.gogradle目录，test.sh没有生成

查看ll ~/.gradle/daemon/4.4/.gogradle/目录，发现该文件生成在该目录下：
test.sh

@blindpirate

**Comment by blindpirate** [comment]
`new File(".gogradle")`相对的不是项目目录，而是JVM进程（Gradle Daemon）的工作路径（`~/.gradle/daemon/4.4/`）。如果你不是对Gradle/JVM的原理非常了解，请不要使用相对路径。

**Comment by JackTiger** [comment]
我的问题，在于arm64系统上，为啥路径会找到~/.gradle/daemon/4.4/.gogradle/ 默认的GRADLE_USER_HOME目录下，而不是我的项目根目录下(其他系统都OK)。

**Comment by JackTiger** [comment]
JVM进程（Gradle Daemon）的工作路径可以自定义和设置吗，x86环境上是没有问题的，只有arm64环境上出现了类似的问题

**Comment by JackTiger** [comment]
每次我们用Java命令运行我们的Java程序，都会在JVM中开启一个进程，对于每一个进程，都会有一个相对应的工作目录，这个工作目录在虚拟机初始化的时候就已经设置好了，默认的情况下，工作目录是我们工程的根目录，

**Comment by blindpirate** [comment]
`new File(".gogradle")`从来不保证是相对于项目目录的。请使用绝对路径`new File(rootProject.projectDir, ".gogradle")`。

**Comment by blindpirate** [comment]
> 每次我们用Java命令运行我们的Java程序，都会在JVM中开启一个进程，对于每一个进程，都会有一个相对应的工作目录，这个工作目录在虚拟机初始化的时候就已经设置好了，默认的情况下，工作目录是我们工程的根目录

你启动的这个JVM进程不执行Gradle构建，只是一个和Gradle Daemon通信的客户端。真正的构建发生在Daemon中，它的工作目录跟项目路径无关。

**Comment by JackTiger** [comment]
感谢你的解答，我不理解，为啥x86上我同样是这样执行的，结果和arm64上的结果不一致，包括我分别在各自的系统上运行同样的任务，X86上是OK的，但是arm64上是有问题的 @blindpirate

**Comment by JackTiger** [comment]
@blindpirate 按照你的建议，是不是只有使用绝对路径才能解决这个问题，即使设置了 System.setProperty("user.dir", "${rootDir}")

**Comment by JackTiger** [comment]
另外咨询下，arm64的环境上是不是只能安装jdk的arm版本？

**Comment by blindpirate** [comment]
> 是不是只有使用绝对路径才能解决这个问题，即使设置了 System.setProperty("user.dir", "${rootDir}")

如果你不是十分确定，请不要使用相对路径。`user.dir`是用户HOME目录，和我们讨论的问题完全是两码事。

> arm64的环境上是不是只能安装jdk的arm版本？

这个问题把我问懵了。。。windows的环境上是不是只能安装jdk的windows版本？
