### ISSUE TITLE
Plugin [id: 'com.github.blindpirate.gogradle', version: '0.11.4'] was not found in any of the following sources:

### ISSUE THREAD

**Issue by jpascal** [gogradle/gogradle#302]
Plugin [id: 'com.github.blindpirate.gogradle', version: '0.11.4'] was not found in any of the following sources:

**Comment by jpascal** [comment]
Is there anyone here?

**Comment by blindpirate** [comment]
Just released: https://plugins.gradle.org/plugin/com.github.blindpirate.gogradle

Thanks for bringing it up.
