### ISSUE TITLE
build failed while fetching metadata on private bitbucket repo 

### ISSUE THREAD

**Issue by siklol** [gogradle/gogradle#58]
Hi,

I tried to build a go project with private bitbucket repos as dependencies. This can't be done, because gogradle tries to fetch metadata from a private bitbucket repo and receives a 403 error.

`12:11:00.241 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@4a08c8885 pairs: {GET /2.0/repositories/xxx/xxx HTTP/1.1: null}{User-Agent: Go-http-client/1.1 Java/1.8.0_121}{Host: api.bitbucket.org}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}`

(I removed the repo and replaced it with xxx)

Based on this https://confluence.atlassian.com/bitbucket/use-the-bitbucket-cloud-rest-apis-222724129.html a basic auth user and password should be provided

**Comment by blindpirate** [comment]
OK, thank you for your information, I have tested Gogradle only with public repo in bitbucket and I will look into this.

**Comment by blindpirate** [comment]
@siklol  Sorry for the late response, but now you can declare a private repository as described [here](https://github.com/blindpirate/gogradle/blob/master/docs/repository-management.md):

```
repositories {
    golang {
        root ~/bitbucket\.org\/myprivaterepo\/[\w-]+/
        vcs 'hg'
        url { 
            "ssh://hg@bitbucket.org/myprivaterepo/${it.split('/')[2]}" 
        }
        
    }
}  
```

Hope that helps.

**Comment by siklol** [comment]
@blindpirate I tried your configuration but it still receives an 403 error.

I think the problem exists in bitbuckets api. Fetching metadata from it via http requests result in the 403 error. You need to specifiy a user and password via basic auth to fix it.

Could you please have a look at it again? Thanks for the help! Really appreciate it

**Comment by blindpirate** [comment]
Do you mind telling me the name of your repository and your repository declarations in your `build.gradle`? I think the repository declaration doesn't match your private repository name.

In my design, if you declared a repository as described above, Gogradle will totally know where to fetch the code then it don't have to request bitbucket api for that information any more.

**Comment by blindpirate** [comment]
Oh, did you put `repository` declaration ahead of your `dependencies` declaration?

**Comment by siklol** [comment]
Hi @blindpirate 

I created a test build with a test repo:

`import com.github.blindpirate.gogradle.Go

plugins {
    id 'com.github.blindpirate.gogradle' version '0.4.2'
}

repositories {
    golang {
        root ~/bitbucket\.org\/veitosiander\/[\w-]+/
        vcs 'git'
        url {
            "ssh://git@bitbucket.org:veitosiander/${it.split('/')[2]}"
        }

    }
}

golang {
    packagePath = 'bitbucket.org/veitosiander/test-bot'
    goVersion = '1.8'
    goRoot = '/usr/lib/go/'
}

dependencies {
    golang {
        build 'github.com/anaskhan96/soup'
        build 'bitbucket.org/veitosiander/de.private.gogradle'
    }
}`

Could you pinpoint my error? Still getting 403 errors

**Comment by blindpirate** [comment]
Regular expression `~/bitbucket\.org\/veitosiander\/[\w-]+/` cannot match `bitbucket.org/veitosiander/de.private.gogradle`. You should use `~/bitbucket\.org\/veitosiander\/[\w.]+/`

**Comment by siklol** [comment]
Thanks! This seems to work. But I get a new problem now: 

`08:17:40.654 [DEBUG] [com.github.blindpirate.gogradle.util.logging.DebugLogMethodInterceptor] Entering method produce of class DefaultPackagePathResolver$$EnhancerByGuice$$fa185ffb, the arguments is [bitbucket.org/veitosiander/de.private.gogradle]
08:17:40.655 [DEBUG] [com.github.blindpirate.gogradle.util.logging.DebugLogMethodInterceptor] Exiting method produce of class DefaultPackagePathResolver$$EnhancerByGuice$$fa185ffb, total time is 0.772 ms, exception is [ClassCastException]org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String
08:17:40.656 [DEBUG] [com.github.blindpirate.gogradle.util.logging.DebugLogMethodInterceptor] Exiting method convert of class DefaultNotationConverter$$EnhancerByGuice$$64689a45, total time is 1.313 ms, exception is [ClassCastException]org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String
08:17:40.656 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 0.117 secs
08:17:40.658 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
08:17:40.659 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
08:17:40.659 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
08:17:40.659 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Where:
08:17:40.659 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Build file '/home/vosiander/go/src/bitbucket.org/veitosiander/rent-bot/build.gradle' line: 27
08:17:40.659 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
08:17:40.659 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
08:17:40.659 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred evaluating root project 'rent-bot'.
08:17:40.659 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String
08:17:40.659 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
08:17:40.659 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
08:17:40.659 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. `

**Comment by blindpirate** [comment]
It seems a misuse of Groovy `GString`. What's there in `'/home/vosiander/go/src/bitbucket.org/veitosiander/rent-bot/build.gradle' line: 27`? Try to add `toString()` to that `GString` like this:

```
"I am a GString with ${value}".toString()
```

**Comment by siklol** [comment]
It's still the same gradle.build file I uploaded earlier. Adding toString() does not work.

It seems to me that the dependency resolver uses the local path but then fails with the error message from above. I tried renaming my project from rent-bot to rentbot and the error message changed to "rentbot".

Do you have any idea?

**Comment by blindpirate** [comment]
Try to add `toString()` in `repositories` like this:

```
repositories {
    golang {
        root ~/bitbucket\.org\/veitosiander\/[\w.]+/
        vcs 'git'
        url {
            "ssh://git@bitbucket.org:veitosiander/${it.split('/')[2]}".toString()
        }

    }
}
```

I didn't take `GString` return value into consideration, and I will fix it in the next release. Thank you for it.

**Comment by siklol** [comment]
Hello!

Sorry, but this still doesn't work with my (work) repositories. I did the regex you mentioned (even simpler ones) and it still does get the 403 error. Could you add some specific code which handles bitbucket repos?

**Comment by blindpirate** [comment]
So you mean it works with your test repository `bitbucket.org/veitosiander/de.private.gogradle` but fails to work with your "working repositories"? What if you just try a string instead of regex like this:

```
repositories {
       golang {
              root 'bitbucket.org/my/privaterepo1'
              url 'ssh://git@bitbucket.org:my/privaterepo1'
       }

       golang {
              root 'bitbucket.org/my/privaterepo2'
              url 'ssh://git@bitbucket.org:my/privaterepo2'
       }
       
       ....
}
```

**Comment by blindpirate** [comment]
Hi, I would close this for the moment, please reopen it if there's any further question.
