### ISSUE TITLE
Build failure when using nebula.ospackage plugin

### ISSUE THREAD

**Issue by srvaroa** [gogradle/gogradle#65]
Hi, I'm trying to get a Go project to build with gogradle, and use nebula.ospackage to create RPM/Deb packages.  

My build works perfectly following the example provided here.  However, if I add nebula.ospackage:

```
plugins {
    id 'nebula.ospackage' version '3.4.0'
    id 'com.github.blindpirate.gogradle' version '0.3.4'
}
golang {
    packagePath = 'github.schibsted.io/spt-engprod/reports-publisher'
}
```

I get the following error

```
* Where:
Build file '/Users/galo/w/go/src/reports-publisher/build.gradle' line: 3

* What went wrong:
An exception occurred applying plugin request [id: 'com.github.blindpirate.gogradle', version: '0.3.4']
> Failed to apply plugin [id 'com.github.blindpirate.gogradle']
   > Declaring custom 'build' task when using the standard Gradle lifecycle plugins is not allowed.
```

Is there a workaround for this? Thanks!

**Comment by blindpirate** [comment]
Looks like name conflict issue. I'm sorry, there's no workaround currently. 

I'm planning to fix it in the next release in one or two days.

**Comment by srvaroa** [comment]
Thanks @blindpirate !

**Comment by blindpirate** [comment]
@srvaroa Sorry for the lateness, I have released `0.4.2` to solve this problem just now, with `build`/`test`/`check`/`clean` task renamed to `goBuild`/`goTest`/`goCheck`/`goClean`. Please see the documentation for more details.

**Comment by srvaroa** [comment]
@blindpirate thanks a lot! I'll let you close this issue if needed :)

**Comment by blindpirate** [comment]
Hi, I would close this for the moment, please reopen it if there's any further question.
